import { useEffect, useState } from 'react';
import { Button, EmptyState, Icon, PageHeader, Panel, Pill, StateBanner } from '../components/ProductUI';

const routeFor={work:'work',project:'projects',pipeline:'pipeline',client:'crm',opportunity:'radar',research:'dashboard'};
const iconFor={work:'check',project:'folder',pipeline:'target',client:'users',opportunity:'target',research:'document'};
export default function AISearch({navigate}){
  const[q,setQ]=useState(''),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(q.trim().length<2){setResults([]);return;}const ctrl=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/search?q=${encodeURIComponent(q.trim())}`,{signal:ctrl.signal});if(!r.ok)throw new Error('Search could not complete.');const d=await r.json();setResults(d.results||[]);}catch(e){if(e.name!=='AbortError')setError(e.message);}setLoading(false);},220);return()=>{clearTimeout(timer);ctrl.abort();};},[q]);
  const go=result=>navigate?.(routeFor[result.type]||'dashboard');
  return <div className="module"><PageHeader eyebrow="Find anything" title="Search JakeOS" subtitle="Search the canonical system across work, projects, pipeline, relationships, opportunities and research."/>{error&&<StateBanner tone="danger" title="Search needs attention">{error}</StateBanner>}<Panel><div className="px-search-input" style={{width:'100%',minWidth:0}}><Icon name="search"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tasks, projects, people, opportunities…"/></div></Panel><div style={{height:14}}/>
    <Panel title={q.trim().length>=2?`Results for “${q.trim()}”`:'Search the command center'} subtitle={loading?'Searching…':results.length?`${results.length} matching records`:'Type at least two characters.'}>{q.trim().length<2?<EmptyState icon="search" title="Search by what you remember" body="A task phrase, organisation, person, project, opportunity or brief title is enough."/>:loading?<div className="px-empty"><div className="px-kicker">Searching JakeOS…</div></div>:results.length===0?<EmptyState icon="search" title="No matching records" body="Try a shorter phrase or search by organisation, project or task wording."/>:<div className="px-list">{results.map((r,i)=><button key={`${r.type}-${r.id}-${i}`} className="px-list-row" onClick={()=>go(r)} style={{width:'100%',textAlign:'left',cursor:'pointer'}}><div className="px-metric-icon" style={{width:38,height:38,margin:0}}><Icon name={iconFor[r.type]||'search'} size={18}/></div><div className="px-list-main"><div className="px-list-title">{r.name||r.title}</div><div className="px-list-sub">{r.subtitle||r.context||'JakeOS record'}</div></div><div className="px-row"><Pill tone={r.type==='work'?'brand':'neutral'}>{r.type}</Pill>{r.status&&<Pill>{r.status}</Pill>}</div></button>)}</div>}</Panel>
  </div>;
}
