import { useCallback, useEffect, useState } from 'react';
import { Button, EmptyState, Icon, LoadingRows, PageHeader, Panel, Pill, StateBanner, formatDate } from '../components/ProductUI';

const LABEL={telegram:'Telegram',whatsapp:'WhatsApp',resend:'Email'};
export default function AlertsSettings(){
  const[integrations,setIntegrations]=useState([]),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sending,setSending]=useState(''),[result,setResult]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([fetch('/api/integrations/status'),fetch('/api/calendar/events')]);const[ia,ca]=await Promise.all([a.json(),b.json()]);setIntegrations(ia.integrations||[]);setEvents((ca.events||[]).filter(x=>!x.done&&new Date(x.starts_at||x.date)>=new Date()).slice(0,8));}catch(e){setError('Alert status could not be loaded.');}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const channels=['telegram','whatsapp','resend'].map(id=>integrations.find(x=>x.id===id)||{id,name:LABEL[id],configured:false,status:'action_required'}),ready=channels.filter(x=>x.configured);
  const test=async channel=>{setSending(channel);setResult('');const backend=channel==='resend'?'email':channel;try{const r=await fetch('/api/alerts/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:backend})});const d=await r.json();setResult(d.ok?`${LABEL[channel]} test sent.`:(d.error||'Test failed.'));}catch(e){setResult(e.message);}setSending('');};
  const digest=async()=>{setSending('digest');setResult('');try{const r=await fetch('/api/alerts/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'digest'})});const d=await r.json();setResult(r.ok?'Digest request completed. Check configured channels.':d.error||'Digest could not be sent.');}catch(e){setResult(e.message);}setSending('');};
  return <div className="module"><PageHeader eyebrow="Notifications" title="Alerts" subtitle="Only configured channels can be tested or used. JakeOS no longer presents setup placeholders as live services." actions={<Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button>}/>{error&&<StateBanner tone="danger" title="Alert status unavailable">{error}</StateBanner>}{result&&<StateBanner tone={result.includes('failed')||result.includes('could not')?'danger':'info'} title="Alert result">{result}</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{ready.length}</div><div className="px-metric-label">Ready channels</div><div className="px-metric-helper">Out of {channels.length}</div></div><div className="px-metric"><div className="px-metric-value">{events.length}</div><div className="px-metric-label">Upcoming commitments</div><div className="px-metric-helper">Potential digest context</div></div><div className="px-metric"><div className="px-metric-value">07:00</div><div className="px-metric-label">Scheduled digest</div><div className="px-metric-helper">Africa/Kampala job cadence</div></div><div className="px-metric"><div className="px-metric-value">{channels.length-ready.length}</div><div className="px-metric-label">Setup needed</div><div className="px-metric-helper">Credentials missing</div></div></div>
    <div className="px-grid-3">{channels.map(ch=><Panel key={ch.id} title={LABEL[ch.id]||ch.name} subtitle={ch.configured?'Server credentials are present.':'Not configured on this JakeOS server.'} action={<Pill tone={ch.configured?'success':'warning'}>{ch.configured?'Ready':'Setup needed'}</Pill>}><div className="px-empty" style={{padding:'18px 4px'}}><div className="px-empty-icon"><Icon name="bell"/></div><p>{ch.id==='telegram'?'Best for fast direct alerts.':ch.id==='whatsapp'?'Optional personal digest channel.':'Useful for longer HTML briefings and records.'}</p><Button variant={ch.configured?'tonal':'secondary'} disabled={!ch.configured||!!sending} onClick={()=>test(ch.id)}>{sending===ch.id?'Testing…':'Test channel'}</Button></div></Panel>)}</div>
    <div style={{height:14}}/><div className="px-grid-2"><Panel title="Next digest context" subtitle="Upcoming JakeOS commitments; the digest generator also uses live finance and deadline data.">{loading?<LoadingRows count={4}/>:events.length?<div className="px-list">{events.map(e=><div className="px-list-row" key={e.id}><div className="px-metric-icon" style={{width:36,height:36,margin:0}}><Icon name="calendar" size={17}/></div><div className="px-list-main"><div className="px-list-title">{e.title}</div><div className="px-list-sub">{e.project||e.type||'JakeOS'}</div></div><div className="px-list-meta">{formatDate(e.starts_at||e.date,{time:!!e.starts_at})}</div></div>)}</div>:<EmptyState icon="calendar" title="No upcoming commitments" body="A digest can still contain work, pipeline and money signals, but calendar context is empty."/>}</Panel><Panel title="Send a digest now" subtitle="This sends only through channels whose server credentials are actually configured.">{ready.length?<><p className="px-muted" style={{fontSize:12,lineHeight:1.55}}>Ready: {ready.map(x=>LABEL[x.id]||x.name).join(', ')}.</p><Button icon="bell" disabled={!!sending} onClick={digest}>{sending==='digest'?'Sending…':'Send digest now'}</Button></>:<EmptyState icon="bell" title="No delivery channel is configured" body="Add Telegram, WhatsApp or email credentials on the server. The Integrations screen will change to Ready automatically."/>}</Panel></div>
  </div>;
}
