import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, Icon, LoadingRows, PageHeader, Panel, Pill, StateBanner, formatDate, relativeDate } from '../components/ProductUI';

const EMPTY={title:'',date:new Date().toISOString().slice(0,10),time:'09:00',project:'',type:'session',notes:'',all_day:false};
const typeTone=t=>t==='deadline'?'danger':t==='milestone'?'warning':t==='meeting'?'info':'neutral';

export default function Calendar({openAI}){
  const[events,setEvents]=useState([]),[gcal,setGcal]=useState({configured:false,connected:false,email:null}),[gcalEvents,setGcalEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState(null),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false),[view,setView]=useState('upcoming');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,b,c]=await Promise.all([fetch('/api/calendar/events'),fetch('/api/gcal/status'),fetch('/api/gcal/events')]);if(!a.ok)throw new Error('Calendar could not be loaded.');const[da,db,dc]=await Promise.all([a.json(),b.json().catch(()=>({})),c.json().catch(()=>({}))]);setEvents(da.events||[]);setGcal(db||{});setGcalEvents(dc.events||[]);}catch(e){setError(e.message);}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const combined=useMemo(()=>[...events.map(x=>({...x,source:x.source||'jakeos'})),...gcalEvents.map(x=>({...x,source:'google'}))].filter((x,i,a)=>a.findIndex(y=>y.id===x.id&&y.source===x.source)===i),[events,gcalEvents]);
  const now=new Date(),upcoming=combined.filter(x=>!x.done&&new Date(x.starts_at||x.date)>=new Date(now.toDateString())).sort((a,b)=>new Date(a.starts_at||a.date)-new Date(b.starts_at||b.date)),today=upcoming.filter(x=>String(x.date||x.starts_at).slice(0,10)===new Date().toISOString().slice(0,10));
  const openNew=()=>{setForm(EMPTY);setDrawer('new');};
  const edit=e=>{if(e.source==='google')return;const d=e.starts_at?new Date(e.starts_at):null;setForm({...EMPTY,...e,date:String(e.date||e.starts_at).slice(0,10),time:d&&!Number.isNaN(d)?d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}):'09:00'});setDrawer(e.id);};
  const save=async()=>{if(!form.title.trim()||!form.date)return;setSaving(true);const starts=form.all_day?null:new Date(`${form.date}T${form.time||'09:00'}:00+03:00`).toISOString();const body={...form,title:form.title.trim(),starts_at:starts,all_day:!!form.all_day};const r=await fetch(drawer==='new'?'/api/calendar/events':`/api/calendar/events/${encodeURIComponent(drawer)}`,{method:drawer==='new'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not save event.');else{setDrawer(null);setForm(EMPTY);await load();}setSaving(false);};
  const toggle=async e=>{if(e.source==='google')return;await fetch(`/api/calendar/events/${encodeURIComponent(e.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({done:!e.done})});await load();};
  const remove=async e=>{if(!confirm(`Delete ${e.title}?`))return;await fetch(`/api/calendar/events/${encodeURIComponent(e.id)}`,{method:'DELETE'});setDrawer(null);await load();};
  const sync=async()=>{const r=await fetch('/api/gcal/sync',{method:'POST'});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Google Calendar sync failed.');else await load();};
  const visible=view==='today'?today:view==='all'?combined:upcoming;
  return <div className="module">
    <PageHeader eyebrow="Time" title="Calendar" subtitle="Commitments and work blocks that constrain what JakeOS should ask of you today." actions={<><Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button><Button icon="plus" onClick={openNew}>Add event</Button></>}/>
    {error&&<StateBanner tone="danger" title="Calendar needs attention">{error}</StateBanner>}
    {!gcal.configured&&<StateBanner tone="info" title="Google Calendar is not connected yet">JakeOS calendar works now with its own events. Server-side Google sync will become available when the OAuth client credentials are configured.</StateBanner>}
    {gcal.configured&&!gcal.connected&&<StateBanner tone="info" title="Google Calendar is ready to connect" action={<Button variant="tonal" onClick={()=>window.location.assign('/auth/google')}>Connect Google</Button>}>Connect once to bring external commitments into JakeOS planning.</StateBanner>}
    {gcal.connected&&<StateBanner tone="success" title={`Google Calendar connected${gcal.email?` · ${gcal.email}`:''}`} action={<Button variant="secondary" onClick={sync}>Sync now</Button>}>JakeOS uses these events when planning the day.</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{today.length}</div><div className="px-metric-label">Today</div><div className="px-metric-helper">Commitments on the day</div></div><div className="px-metric"><div className="px-metric-value">{upcoming.length}</div><div className="px-metric-label">Upcoming</div><div className="px-metric-helper">Open future events</div></div><div className="px-metric"><div className="px-metric-value">{events.filter(x=>x.source!=='google').length}</div><div className="px-metric-label">JakeOS events</div><div className="px-metric-helper">Canonical local calendar</div></div><div className="px-metric"><div className="px-metric-value">{gcalEvents.length}</div><div className="px-metric-label">Google events</div><div className="px-metric-helper">{gcal.connected?'Synced':'Not connected'}</div></div></div>
    <Panel title="Schedule" subtitle="Use the view that matches the decision you are making." action={<div className="px-row">{['today','upcoming','all'].map(v=><Button key={v} variant={view===v?'tonal':'ghost'} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</Button>)}</div>}>
      {loading?<LoadingRows count={6}/>:visible.length===0?<EmptyState icon="calendar" title={view==='today'?'Nothing scheduled today':'No events in this view'} body="Add an event when a commitment truly constrains your time. Tasks belong in Work, not the calendar." action={<Button variant="tonal" onClick={openNew}>Add event</Button>}/>:<div className="px-list">{visible.map(event=><button className="px-list-row" key={`${event.source}-${event.id}`} onClick={()=>edit(event)} style={{width:'100%',textAlign:'left',cursor:event.source==='google'?'default':'pointer'}}><div className="px-metric-icon" style={{margin:0,width:38,height:38,background:event.source==='google'?'var(--px-success-soft)':'var(--px-brand-soft)',color:event.source==='google'?'var(--px-success)':'var(--px-brand)'}}><Icon name="calendar" size={18}/></div><div className="px-list-main"><div className="px-list-title">{event.title}</div><div className="px-list-sub">{event.project||event.source}{event.notes?` · ${event.notes}`:''}</div><div className="px-task-meta"><Pill tone={typeTone(event.type)}>{event.type||'event'}</Pill>{event.source==='google'&&<Pill tone="success">Google</Pill>}</div></div><div className="px-list-meta">{event.starts_at?formatDate(event.starts_at,{time:true}):formatDate(event.date)}<div style={{marginTop:4}}>{relativeDate(event.starts_at||event.date)}</div></div></button>)}</div>}
    </Panel>
    {drawer&&<div className="px-drawer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><div className="px-drawer-card"><PageHeader eyebrow="Commitment" title={drawer==='new'?'Add event':'Edit event'} subtitle="Reserve calendar space for real commitments. Use Work for flexible tasks." actions={<button className="px-icon-button" onClick={()=>setDrawer(null)}>×</button>}/><div className="px-stack"><div className="px-field"><label>Title</label><input autoFocus value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div className="px-form-grid"><div className="px-field"><label>Date</label><input type="date" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))}/></div><div className="px-field"><label>Time</label><input type="time" disabled={form.all_day} value={form.time||''} onChange={e=>setForm(f=>({...f,time:e.target.value}))}/></div></div><div className="px-form-grid"><div className="px-field"><label>Project / label</label><input value={form.project||''} onChange={e=>setForm(f=>({...f,project:e.target.value}))}/></div><div className="px-field"><label>Type</label><select value={form.type||'session'} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>{['session','meeting','deadline','milestone','travel','personal'].map(x=><option key={x}>{x}</option>)}</select></div></div><label className="px-row" style={{fontSize:12,color:'var(--px-muted)'}}><input type="checkbox" checked={!!form.all_day} onChange={e=>setForm(f=>({...f,all_day:e.target.checked}))}/> All-day commitment</label><div className="px-field"><label>Notes</label><textarea value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></div></div><div className="px-form-actions">{drawer!=='new'&&<Button variant="danger" onClick={()=>remove(form)}>Delete</Button>}<span style={{flex:1}}/>{drawer!=='new'&&<Button variant="secondary" onClick={()=>toggle(form)}>{form.done?'Mark open':'Mark done'}</Button>}<Button onClick={save} disabled={saving}>{saving?'Saving…':'Save event'}</Button></div></div></div>}
  </div>;
}
