import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, LoadingRows, Metric, PageHeader, Panel, Pill, StateBanner, formatMoney, formatDate } from '../components/ProductUI';

const age=value=>{if(!value)return 'No activity yet';const ms=Date.now()-new Date(value).getTime();if(ms<60000)return 'Just now';if(ms<3600000)return `${Math.floor(ms/60000)}m ago`;if(ms<86400000)return `${Math.floor(ms/3600000)}h ago`;return `${Math.floor(ms/86400000)}d ago`;};
const growthTone=n=>Number(n)>0?'success':Number(n)<0?'danger':'neutral';
export default function Estate({compact=false}){
  const[state,setState]=useState({loading:true,data:null,error:''});
  const load=useCallback(async(force=false)=>{setState(s=>({...s,loading:!s.data,error:''}));try{const r=await fetch(`/api/estate${force?'?refresh=1':''}`),d=await r.json();if(!r.ok&&!d.snapshot)throw new Error(d.error||'Estate telemetry unavailable');setState({loading:false,data:d,error:d.error||''});}catch(e){setState(s=>({...s,loading:false,error:e.message}))}},[]);useEffect(()=>{load();const t=setInterval(()=>load(false),60000);return()=>clearInterval(t);},[load]);
  const snap=state.data?.snapshot,products=snap?.products||[],commerce=snap?.commerce||[],totals=snap?.totals||{},kela=commerce.find(x=>x.productCode==='kela');
  const sorted=useMemo(()=>[...products].sort((a,b)=>Number(b.activeUsers7d)-Number(a.activeUsers7d)),[products]);
  if(compact)return snap?<div className="px-grid-3"><Metric label="Active users / 7d" value={totals.activeUsers7d||0}/><Metric label="Live orders" value={totals.ordersActive||0}/><Metric label="Realized" value={formatMoney(totals.realizedRevenueUGX||0,'UGX')}/></div>:null;
  return <div className="module"><PageHeader eyebrow="Portfolio intelligence" title="Tuku Estate" subtitle="Observed product usage, growth, orders and earnings across the estate. Entitled reach stays separate from actual activity." actions={<Button variant="secondary" icon="refresh" onClick={()=>load(true)}>Refresh now</Button>}/>{state.error&&<StateBanner tone={snap?'warning':'danger'} title={snap?'Using the last successful estate snapshot':'Estate telemetry unavailable'}>{state.error}</StateBanner>}{state.data?.stale&&<StateBanner tone="warning" title="Cached telemetry">Last successful refresh {state.data.lastSuccessfulAt?age(state.data.lastSuccessfulAt):'at an unknown time'}. JakeOS will not turn a feed failure into false zeros.</StateBanner>}
    <div className="px-metrics"><Metric icon="users" label="Active users / 24h" value={totals.activeUsers24h||0} helper="Observed use across products"/><Metric icon="users" label="Active users / 7d" value={totals.activeUsers7d||0} helper="Estate activity window" tone="success"/><Metric icon="target" label="Live orders" value={totals.ordersActive||0} helper={`${totals.ordersCompleted||0} fulfilled`} tone="warning"/><Metric icon="money" label="Realized earnings" value={formatMoney(totals.realizedRevenueUGX||0,'UGX')} helper={`${formatMoney(totals.pendingRevenueUGX||0,'UGX')} pending`} tone="success"/></div>
    <Panel title="Product usage" subtitle="Actual activity by tool. Reach is entitlement/access, not a substitute for usage.">{state.loading&&!snap?<LoadingRows count={7}/>:sorted.length?<div style={{overflowX:'auto'}}><table className="finance-table" style={{minWidth:760}}><thead><tr><th>Product</th><th>Reach</th><th>24h</th><th>7d</th><th>30d</th><th>New / 7d</th><th>Growth</th><th>Last activity</th></tr></thead><tbody>{sorted.map(p=><tr key={p.code}><td><strong>{p.name}</strong><div className="px-kicker">{p.code}</div></td><td>{Number(p.reach?.users||0).toLocaleString()}</td><td>{Number(p.activeUsers24h||0).toLocaleString()}</td><td><strong>{Number(p.activeUsers7d||0).toLocaleString()}</strong></td><td>{Number(p.activeUsers30d||0).toLocaleString()}</td><td>{Number(p.newUsers7d||0).toLocaleString()}</td><td><Pill tone={growthTone(p.growth7dPercent)}>{Number(p.growth7dPercent||0)>0?'+':''}{Number(p.growth7dPercent||0).toFixed(1)}%</Pill></td><td>{age(p.lastActivityAt)}</td></tr>)}</tbody></table></div>:<EmptyState icon="estate" title="No product usage reported" body="The Estate connection is live, but no product has reported observed usage in this snapshot."/>}</Panel>
    <div style={{height:16}}/><div className="px-grid-2"><Panel title="Orders & earnings" subtitle="Commercial activity reported by each product.">{commerce.length?<div className="px-list">{commerce.map(c=><div className="px-list-row" key={`${c.productCode}-${c.currency}`}><div className="px-list-main"><div className="px-list-title" style={{textTransform:'capitalize'}}>{c.productCode}</div><div className="px-list-sub">{c.orders?.active||0} live · {c.orders?.completed||0} fulfilled · last order {c.lastOrderAt?age(c.lastOrderAt):'not reported'}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,fontWeight:750,color:'var(--px-success)'}}>{formatMoney(c.earnings?.realized||0,c.currency||'UGX')}</div><div className="px-kicker">{formatMoney(c.earnings?.pending||0,c.currency||'UGX')} pending</div></div></div>)}</div>:<EmptyState icon="money" title="No commerce activity reported" body="Order and earnings feeds will appear here as products send canonical commerce events."/>}</Panel>
      <Panel title="Kela operations" subtitle="Live fulfilment state from Kela's canonical errands table.">{kela?<div className="px-grid-3">{[['New',kela.orders?.new],['Sourcing',kela.orders?.sourcing],['Shopping',kela.orders?.shopping],['Consolidation',kela.orders?.consolidation],['Ready',kela.orders?.ready],['Delivery',kela.orders?.outForDelivery],['Completed',kela.orders?.completed]].map(([label,value])=><div className="px-panel" key={label} style={{padding:13,boxShadow:'none'}}><div className="px-metric-value" style={{fontSize:20}}>{value||0}</div><div className="px-kicker">{label}</div></div>)}</div>:<EmptyState icon="target" title="Kela feed unavailable" body="The estate snapshot did not include Kela commerce state."/>}</Panel></div>
    <div className="px-kicker" style={{marginTop:12}}>Snapshot generated {snap?.generatedAt?formatDate(snap.generatedAt,{year:true,time:true}):'—'} · JakeOS refreshes the cached view approximately every minute.</div>
  </div>;
}
