import { useState } from 'react';
import { Button, Icon, PageHeader, Panel, StateBanner } from '../components/ProductUI';

const csv=(rows,cols)=>[cols.map(c=>`"${c.label}"`).join(','),...rows.map(r=>cols.map(c=>`"${String(typeof c.get==='function'?c.get(r):(r[c.key]??'')).replace(/"/g,'""')}"`).join(','))].join('\n');
const download=(name,content,type='text/csv;charset=utf-8')=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),800);};
const get=async path=>{const r=await fetch(path);const d=await r.json();if(!r.ok)throw new Error(d.error||`Could not export ${path}`);return d;};
export default function ExportCentre(){
  const[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const run=async(id,fn)=>{setBusy(id);setMessage('');try{await fn();setMessage('Export prepared from live JakeOS data.');}catch(e){setMessage(e.message||'Export failed.');}setBusy('');};
  const exports=[
    {id:'work',title:'Work items',desc:'Canonical tasks with status, priority, project, due dates and completion.',icon:'check',fn:async()=>{const d=await get('/api/work/items?limit=500');download('jakeos_work.csv',csv(d.items||[],[{label:'Title',key:'title'},{label:'Project',key:'project_name'},{label:'Status',key:'status'},{label:'Priority',key:'priority'},{label:'Due',key:'due_at'},{label:'Estimate minutes',key:'estimated_minutes'},{label:'Blocked',get:x=>x.blocked?'Yes':'No'}]));}},
    {id:'projects',title:'Projects',desc:'Project health, open work, blockers and next due date.',icon:'folder',fn:async()=>{const d=await get('/api/work/projects');download('jakeos_projects.csv',csv(d.projects||[],[{label:'Project',key:'name'},{label:'Status',key:'status'},{label:'Priority',key:'priority'},{label:'Open tasks',key:'open_tasks'},{label:'Doing',key:'doing_tasks'},{label:'Blocked',key:'blocked_tasks'},{label:'Completed',key:'completed_tasks'},{label:'Next due',key:'next_due_at'}]));}},
    {id:'pipeline',title:'Pipeline',desc:'Business-development pursuits, values, stages, deadlines and contacts.',icon:'target',fn:async()=>{const d=await get('/api/pipeline');download('jakeos_pipeline.csv',csv(d.pipeline||[],[{label:'Name',key:'name'},{label:'Organisation',key:'org'},{label:'Stage',key:'stage'},{label:'Type',key:'type'},{label:'Value USD',key:'valueUSD'},{label:'Deadline',key:'deadline'},{label:'Contact',key:'contact'},{label:'Notes',key:'notes'}]));}},
    {id:'calendar',title:'Calendar',desc:'JakeOS calendar events and commitments.',icon:'calendar',fn:async()=>{const d=await get('/api/calendar/events');download('jakeos_calendar.csv',csv(d.events||[],[{label:'Title',key:'title'},{label:'Date',key:'date'},{label:'Start',key:'starts_at'},{label:'Type',key:'type'},{label:'Project',key:'project'},{label:'Done',get:x=>x.done?'Yes':'No'},{label:'Notes',key:'notes'}]));}},
    {id:'crm',title:'Relationships',desc:'CRM contacts, organisations and follow-up fields.',icon:'users',fn:async()=>{const d=await get('/api/crm/clients');download('jakeos_relationships.csv',csv(d.clients||[],[{label:'Name',key:'name'},{label:'Organisation',key:'org'},{label:'Role',key:'role'},{label:'Type',key:'type'},{label:'Email',key:'email'},{label:'Phone',key:'phone'},{label:'Last contact',key:'last_contact'},{label:'Next follow-up',key:'next_followup'}]));}},
    {id:'finance',title:'Revenue plan',desc:'Revenue streams and targets from PostgreSQL.',icon:'money',fn:async()=>{const d=await get('/api/finance');download('jakeos_revenue.csv',csv(d.streams||[],[{label:'Source',key:'name'},{label:'Type',key:'type'},{label:'Status',key:'status'},{label:'Amount',key:'amount'},{label:'Currency',key:'currency'},{label:'Period',key:'month'}]));}},
    {id:'invoices',title:'Invoices',desc:'Invoice register with client, status, total and due dates.',icon:'document',fn:async()=>{const d=await get('/api/invoices');download('jakeos_invoices.csv',csv(d.invoices||[],[{label:'Number',get:x=>x.number||x.invoice_number},{label:'Client',key:'client_name'},{label:'Status',key:'status'},{label:'Total',key:'total'},{label:'Currency',key:'currency'},{label:'Due',key:'due_date'}]));}},
    {id:'grants',title:'Grants & bids',desc:'Chosen grant/tender pursuits and submission stages.',icon:'document',fn:async()=>{const d=await get('/api/grants');download('jakeos_grants_bids.csv',csv(d.grants||[],[{label:'Title',key:'title'},{label:'Funder',key:'funder'},{label:'Type',key:'type'},{label:'Sector',key:'sector'},{label:'Stage',key:'stage'},{label:'Amount',key:'amount'},{label:'Currency',key:'currency'},{label:'Deadline',key:'deadline'}]));}},
  ];
  return <div className="module"><PageHeader eyebrow="Portability" title="Export" subtitle="Download live canonical JakeOS data. Exports are generated in your browser from authenticated API responses."/>{message&&<StateBanner tone={message.includes('failed')||message.includes('Could not')?'danger':'success'} title="Export">{message}</StateBanner>}<div className="px-grid-3">{exports.map(x=><Panel key={x.id} title={x.title} subtitle={x.desc}><div className="px-empty" style={{padding:'18px 4px'}}><div className="px-empty-icon"><Icon name={x.icon}/></div><Button variant="tonal" icon="upload" disabled={!!busy} onClick={()=>run(x.id,x.fn)}>{busy===x.id?'Preparing…':'Download CSV'}</Button></div></Panel>)}</div></div>;
}
