import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, PageHeader, Panel, Pill, StateBanner, formatMoney } from '../components/ProductUI';

const STREAM={name:'',type:'Consulting',status:'Projected',amount:'',currency:'USD',month:''};
const EXPENSE={name:'',amount:'',currency:'USD',monthly:true,category:'Operations'};
export default function Finance({openAI}){
  const[data,setData]=useState({streams:[],expenses:[],targets:{quarterly:20000,annual:100000,currency:'USD'}}),[error,setError]=useState(''),[drawer,setDrawer]=useState(null),[form,setForm]=useState({}),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const r=await fetch('/api/finance');if(!r.ok)throw new Error('Revenue plan could not be loaded.');setData(await r.json());}catch(e){setError(e.message);}},[]);useEffect(()=>{load();},[load]);
  const confirmed=useMemo(()=>data.streams.filter(x=>x.status==='Confirmed').reduce((s,x)=>s+Number(x.amount||0),0),[data]),pending=useMemo(()=>data.streams.filter(x=>x.status==='Pending').reduce((s,x)=>s+Number(x.amount||0),0),[data]),projected=useMemo(()=>data.streams.filter(x=>x.status==='Projected').reduce((s,x)=>s+Number(x.amount||0),0),[data]),monthly=useMemo(()=>data.expenses.filter(x=>x.monthly).reduce((s,x)=>s+Number(x.amount||0),0),[data]);
  const open=(kind,item)=>{setDrawer({kind,id:item?.id||'new'});setForm(item?{...item}:{...(kind==='stream'?STREAM:kind==='expense'?EXPENSE:data.targets)});};
  const save=async()=>{setSaving(true);let url,method;if(drawer.kind==='target'){url='/api/finance/targets';method='PATCH';}else{const plural=drawer.kind==='stream'?'streams':'expenses';url=drawer.id==='new'?`/api/finance/${plural}`:`/api/finance/${plural}/${encodeURIComponent(drawer.id)}`;method=drawer.id==='new'?'POST':'PATCH';}const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not save finance data.');else{setDrawer(null);await load();}setSaving(false);};
  const remove=async()=>{if(!confirm('Delete this record?'))return;const plural=drawer.kind==='stream'?'streams':'expenses';await fetch(`/api/finance/${plural}/${encodeURIComponent(drawer.id)}`,{method:'DELETE'});setDrawer(null);await load();};
  const q=Number(data.targets?.quarterly||0),pct=q?Math.min(100,Math.round(confirmed/q*100)):0;
  return <div className="module"><PageHeader eyebrow="Money" title="Revenue plan" subtitle="Durable revenue streams, operating costs and targets. Cash-flow and invoices remain separate operational views." actions={<><Button variant="secondary" onClick={()=>open('target',data.targets)}>Edit targets</Button><Button icon="plus" onClick={()=>open('stream')}>Revenue</Button></>}/>{error&&<StateBanner tone="danger" title="Money data needs attention">{error}</StateBanner>}
    <div className="px-metrics"><div className="px-metric px-metric--success"><div className="px-metric-value">{formatMoney(confirmed,'USD')}</div><div className="px-metric-label">Confirmed</div><div className="px-metric-helper">{pct}% of quarterly target</div></div><div className="px-metric px-metric--warning"><div className="px-metric-value">{formatMoney(pending,'USD')}</div><div className="px-metric-label">Pending</div><div className="px-metric-helper">Expected but not secure</div></div><div className="px-metric"><div className="px-metric-value">{formatMoney(projected,'USD')}</div><div className="px-metric-label">Projected</div><div className="px-metric-helper">Planning assumption</div></div><div className="px-metric"><div className="px-metric-value">{formatMoney(monthly,'USD')}</div><div className="px-metric-label">Monthly costs</div><div className="px-metric-helper">Recurring baseline</div></div></div>
    <div className="finance-grid"><Panel title="Revenue streams" subtitle="What is confirmed, pending or projected." action={<Button variant="ghost" icon="spark" onClick={()=>openAI(`Revenue: confirmed ${confirmed} USD, pending ${pending}, projected ${projected}, target ${q}. Analyse the gap and the fastest credible paths to close it.`)}>Review</Button>}>{data.streams.length?<div style={{overflowX:'auto'}}><table className="finance-table"><thead><tr><th>Source</th><th>Type</th><th>Status</th><th>Amount</th><th>Period</th></tr></thead><tbody>{data.streams.map(x=><tr key={x.id} onClick={()=>open('stream',x)} style={{cursor:'pointer'}}><td><strong>{x.name}</strong></td><td>{x.type}</td><td><Pill tone={x.status==='Confirmed'?'success':x.status==='Pending'?'warning':'neutral'}>{x.status}</Pill></td><td>{formatMoney(x.amount,x.currency||'USD')}</td><td>{x.month||'—'}</td></tr>)}</tbody></table></div>:<EmptyState icon="money" title="No revenue streams" body="Add only real or planned revenue sources you want JakeOS to track." action={<Button variant="tonal" onClick={()=>open('stream')}>Add revenue</Button>}/>}</Panel><div className="px-stack"><Panel title="Quarterly target" subtitle="Confirmed revenue against the current target."><div className="px-metric-value">{formatMoney(q,data.targets?.currency||'USD')}</div><div className="progress-bar progress-bar--lg" style={{marginTop:14}}><div className="progress-fill" style={{width:`${pct}%`,background:'var(--px-brand)'}}/></div><div className="px-between" style={{marginTop:8}}><span className="px-kicker">{pct}% confirmed</span><span className="px-kicker">Gap {formatMoney(Math.max(0,q-confirmed),'USD')}</span></div></Panel><Panel title="Expenses" subtitle={`${formatMoney(monthly,'USD')} recurring each month.`} action={<Button variant="ghost" icon="plus" onClick={()=>open('expense')}>Add</Button>}>{data.expenses.length?<div className="px-list">{data.expenses.map(x=><button className="px-list-row" key={x.id} style={{width:'100%',textAlign:'left',cursor:'pointer'}} onClick={()=>open('expense',x)}><div className="px-list-main"><div className="px-list-title">{x.name}</div><div className="px-list-sub">{x.category} · {x.monthly?'Monthly':'One-time'}</div></div><strong>{formatMoney(x.amount,x.currency||'USD')}</strong></button>)}</div>:<EmptyState icon="money" title="No expenses" body="Add recurring costs to make revenue targets and runway more realistic."/>}</Panel></div></div>
    {drawer&&<div className="px-drawer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><div className="px-drawer-card"><PageHeader eyebrow="Money" title={drawer.kind==='target'?'Revenue targets':drawer.kind==='stream'?'Revenue stream':'Expense'} subtitle="These values are stored in JakeOS PostgreSQL and drive command-center decisions." actions={<button className="px-icon-button" onClick={()=>setDrawer(null)}>×</button>}/><div className="px-stack">{drawer.kind==='stream'&&<><div className="px-field"><label>Name</label><input value={form.name||''} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></div><div className="px-form-grid"><div className="px-field"><label>Status</label><select value={form.status||'Projected'} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{['Confirmed','Pending','Projected'].map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Type</label><input value={form.type||''} onChange={e=>setForm(f=>({...f,type:e.target.value}))}/></div></div></>}{drawer.kind==='expense'&&<><div className="px-field"><label>Name</label><input value={form.name||''} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></div><div className="px-field"><label>Category</label><input value={form.category||''} onChange={e=>setForm(f=>({...f,category:e.target.value}))}/></div></>}{drawer.kind==='target'?<div className="px-form-grid"><div className="px-field"><label>Quarterly target</label><input type="number" value={form.quarterly||0} onChange={e=>setForm(f=>({...f,quarterly:Number(e.target.value)}))}/></div><div className="px-field"><label>Annual target</label><input type="number" value={form.annual||0} onChange={e=>setForm(f=>({...f,annual:Number(e.target.value)}))}/></div></div>:<div className="px-form-grid"><div className="px-field"><label>Amount</label><input type="number" value={form.amount||''} onChange={e=>setForm(f=>({...f,amount:Number(e.target.value)}))}/></div><div className="px-field"><label>Currency</label><select value={form.currency||'USD'} onChange={e=>setForm(f=>({...f,currency:e.target.value}))}>{['USD','UGX','EUR','GBP','KES'].map(x=><option key={x}>{x}</option>)}</select></div></div>}{drawer.kind==='stream'&&<div className="px-field"><label>Period</label><input value={form.month||''} onChange={e=>setForm(f=>({...f,month:e.target.value}))} placeholder="e.g. Sep 2026 or Q4 2026"/></div>}{drawer.kind==='expense'&&<label className="px-row"><input type="checkbox" checked={!!form.monthly} onChange={e=>setForm(f=>({...f,monthly:e.target.checked}))}/> Recurring monthly</label>}</div><div className="px-form-actions">{drawer.id!=='new'&&drawer.kind!=='target'&&<Button variant="danger" onClick={remove}>Delete</Button>}<span style={{flex:1}}/><Button variant="secondary" onClick={()=>setDrawer(null)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving?'Saving…':'Save'}</Button></div></div></div>}
  </div>;
}
