import { useCallback, useEffect, useMemo, useState } from 'react';
import { askClaude } from '../api/claude';
import { Button, EmptyState, LoadingRows, PageHeader, Panel, Pill, StateBanner, formatMoney, relativeDate } from '../components/ProductUI';

const STAGES=['Identified','LOI Submitted','Full Application','Under Review','Awarded','Rejected','Reporting'];
const TYPES=['Grant','Tender','RFP','Co-funding','Prize'];
const SECTORS=['Agriculture','Health','Education','Technology','Gender','Climate','MSME','Youth','Other'];
const CHECKS=['Read full guidelines','Register on funder portal','Write LOI / concept note','Prepare organisation profile','Collect supporting documents','Budget prepared','Submit application','Confirmation received'];
const EMPTY={title:'',funder:'',amount:'',currency:'USD',type:'Grant',sector:'MSME',stage:'Identified',deadline:'',contact:'',website:'',notes:'',context:'',checklist:[]};
const tone=s=>s==='Awarded'?'success':s==='Rejected'?'danger':['Full Application','Under Review'].includes(s)?'warning':s==='LOI Submitted'?'info':'neutral';

export default function Grants(){
  const[grants,setGrants]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[drawer,setDrawer]=useState(null),[form,setForm]=useState(EMPTY),[busy,setBusy]=useState(false),[aiReady,setAiReady]=useState(false),[fx,setFx]=useState({});
  const load=useCallback(async()=>{setLoading(true);try{const[a,b,c]=await Promise.all([fetch('/api/grants'),fetch('/api/integrations/status'),fetch('/api/fx-rates?base=USD')]);const[ga,ii,ff]=await Promise.all([a.json(),b.json(),c.json()]);setGrants(ga.grants||[]);setAiReady((ii.integrations||[]).find(x=>x.id==='anthropic')?.configured===true);setFx(ff.rates||{});}catch(e){setError('Grants and bids could not be loaded.');}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const current=grants.find(x=>x.id===selected)||null;
  const usd=x=>{const amount=Number(x.amount||0),cur=x.currency||'USD';if(cur==='USD')return amount;return fx[cur]?amount/Number(fx[cur]):0;};
  const openValue=useMemo(()=>grants.filter(x=>!['Awarded','Rejected','Reporting'].includes(x.stage)).reduce((s,x)=>s+usd(x),0),[grants,fx]);
  const awarded=useMemo(()=>grants.filter(x=>x.stage==='Awarded').reduce((s,x)=>s+usd(x),0),[grants,fx]);
  const dueSoon=grants.filter(x=>x.deadline&&!['Awarded','Rejected'].includes(x.stage)&&new Date(x.deadline)<=new Date(Date.now()+14*86400000)).length;
  const edit=g=>{setForm({...EMPTY,...g,checklist:Array.isArray(g.checklist)?g.checklist:[]});setDrawer(g.id);};const openNew=()=>{setForm(EMPTY);setDrawer('new');};
  const save=async()=>{if(!form.title.trim()||!form.funder.trim())return;setBusy(true);const r=await fetch(drawer==='new'?'/api/grants':`/api/grants/${encodeURIComponent(drawer)}`,{method:drawer==='new'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,amount:Number(form.amount)||0})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Grant or bid could not be saved.');else{setDrawer(null);await load();setSelected(d.grant?.id||selected);}setBusy(false);};
  const patch=async(g,change)=>{await fetch(`/api/grants/${encodeURIComponent(g.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(change)});await load();};
  const remove=async g=>{if(!confirm(`Delete ${g.title}?`))return;await fetch(`/api/grants/${encodeURIComponent(g.id)}`,{method:'DELETE'});setSelected(null);await load();};
  const toggleCheck=async(g,item)=>{const list=Array.isArray(g.checklist)?g.checklist:[],found=list.find(x=>x.item===item),next=found?list.map(x=>x.item===item?{...x,done:!x.done}:x):[...list,{item,done:true}];await patch(g,{checklist:next});};
  const draftLoi=async()=>{if(!current||!aiReady)return;setBusy(true);const reply=await askClaude([{role:'user',content:'Draft a concise, professional one-page letter of intent. Include who we are, the proposed response, expected result, budget/value where known and a clear next step. Do not invent eligibility, achievements or evidence.'}],'grants',`Opportunity: ${current.title}. Funder: ${current.funder}. Type: ${current.type}. Sector: ${current.sector}. Amount: ${current.amount} ${current.currency}. Deadline: ${current.deadline||'unknown'}. Notes: ${current.notes||''}. Source context: ${current.context||''}.`);await patch(current,{notes:`${current.notes||''}\n\n--- AI LOI DRAFT ---\n${reply}`.trim()});setBusy(false);};
  return <div className="module"><PageHeader eyebrow="Opportunity delivery" title="Grants & bids" subtitle="A durable pursuit register for calls you have decided to work—not a duplicate of Radar discovery." actions={<Button icon="plus" onClick={openNew}>Add pursuit</Button>}/>{error&&<StateBanner tone="danger" title="Grant data needs attention">{error}</StateBanner>}{!aiReady&&<StateBanner tone="info" title="AI drafting is not configured">Tracking, checklists, deadlines and notes are fully available. LOI drafting will activate when AI credentials are configured.</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{grants.filter(x=>!['Awarded','Rejected'].includes(x.stage)).length}</div><div className="px-metric-label">Open pursuits</div><div className="px-metric-helper">Actively considered or submitted</div></div><div className="px-metric px-metric--warning"><div className="px-metric-value">{formatMoney(openValue,'USD')}</div><div className="px-metric-label">Open value</div><div className="px-metric-helper">Approx. USD using current FX</div></div><div className="px-metric px-metric--success"><div className="px-metric-value">{formatMoney(awarded,'USD')}</div><div className="px-metric-label">Awarded</div><div className="px-metric-helper">Approx. USD equivalent</div></div><div className={`px-metric ${dueSoon?'px-metric--danger':''}`}><div className="px-metric-value">{dueSoon}</div><div className="px-metric-label">Deadlines / 14d</div><div className="px-metric-helper">Needs submission discipline</div></div></div>
    <div className="px-grid-2"><Panel title="Pursuit register" subtitle="Radar finds possibilities; this list is what you have chosen to work.">{loading?<LoadingRows count={6}/>:grants.length===0?<EmptyState icon="document" title="No grant or bid pursuits" body="Add an opportunity only after deciding it deserves delivery effort." action={<Button variant="tonal" onClick={openNew}>Add pursuit</Button>}/>:<div className="px-list">{grants.map(g=><button key={g.id} className="px-list-row" style={{width:'100%',textAlign:'left',cursor:'pointer',borderColor:selected===g.id?'rgba(36,92,70,.35)':undefined}} onClick={()=>setSelected(g.id)}><div className="px-list-main"><div className="px-list-title">{g.title}</div><div className="px-list-sub">{g.funder} · {g.type} · {g.sector}</div><div className="px-task-meta"><Pill tone={tone(g.stage)}>{g.stage}</Pill>{g.deadline&&<Pill tone={new Date(g.deadline)<new Date()&&!['Awarded','Rejected'].includes(g.stage)?'danger':'neutral'}>{relativeDate(g.deadline)}</Pill>}</div></div><div className="px-list-meta">{Number(g.amount)>0?formatMoney(g.amount,g.currency):'Value TBD'}</div></button>)}</div>}</Panel>
      <Panel title={current?.title||'Pursuit detail'} subtitle={current?`${current.funder} · ${current.stage}`:'Choose a pursuit to see its delivery checklist.'}>{current?<><div className="px-between"><div className="px-row"><Pill tone={tone(current.stage)}>{current.stage}</Pill>{current.deadline&&<Pill>{relativeDate(current.deadline)}</Pill>}</div><Button variant="secondary" onClick={()=>edit(current)}>Edit</Button></div>{current.notes&&<p className="px-muted" style={{whiteSpace:'pre-wrap',fontSize:12,lineHeight:1.55}}>{current.notes}</p>}<div className="px-divider"/><div className="px-list-title" style={{marginBottom:8}}>Submission checklist</div><div className="px-list">{CHECKS.map(item=>{const done=(current.checklist||[]).find(x=>x.item===item)?.done;return <button key={item} className="px-list-row" style={{width:'100%',textAlign:'left',cursor:'pointer'}} onClick={()=>toggleCheck(current,item)}><span className="px-check" style={done?{background:'var(--px-brand)',color:'#fff',borderColor:'var(--px-brand)'}:{}}>{done?'✓':''}</span><div className="px-list-main"><div className="px-list-title" style={done?{textDecoration:'line-through',color:'var(--px-dim)'}:{}}>{item}</div></div></button>})}</div><div className="px-form-actions" style={{justifyContent:'flex-start'}}><Button variant="tonal" icon="spark" disabled={!aiReady||busy} onClick={draftLoi}>{busy?'Drafting…':'Draft LOI'}</Button>{current.website&&<Button variant="secondary" onClick={()=>window.open(current.website,'_blank','noopener')}>Open source</Button>}<Button variant="ghost" onClick={()=>remove(current)}>Delete</Button></div></>:<EmptyState icon="document" title="Choose a pursuit" body="The detail view keeps deadline, evidence context and submission work together."/>}</Panel></div>
    {drawer&&<div className="px-drawer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><div className="px-drawer-card"><PageHeader eyebrow="Pursuit" title={drawer==='new'?'Add grant or bid':'Edit pursuit'} subtitle="Capture the source faithfully. Do not turn assumptions into eligibility facts." actions={<button className="px-icon-button" onClick={()=>setDrawer(null)}>×</button>}/><div className="px-stack"><div className="px-field"><label>Opportunity title</label><input autoFocus value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div className="px-field"><label>Funder / issuer</label><input value={form.funder} onChange={e=>setForm(f=>({...f,funder:e.target.value}))}/></div><div className="px-form-grid"><div className="px-field"><label>Type</label><select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Sector</label><select value={form.sector} onChange={e=>setForm(f=>({...f,sector:e.target.value}))}>{SECTORS.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="px-form-grid"><div className="px-field"><label>Stage</label><select value={form.stage} onChange={e=>setForm(f=>({...f,stage:e.target.value}))}>{STAGES.map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Deadline</label><input type="date" value={form.deadline||''} onChange={e=>setForm(f=>({...f,deadline:e.target.value}))}/></div></div><div className="px-form-grid"><div className="px-field"><label>Amount</label><input type="number" min="0" value={form.amount||''} onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></div><div className="px-field"><label>Currency</label><select value={form.currency} onChange={e=>setForm(f=>({...f,currency:e.target.value}))}>{['USD','UGX','EUR','GBP','KES'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="px-field"><label>Source URL</label><input value={form.website||''} onChange={e=>setForm(f=>({...f,website:e.target.value}))}/></div><div className="px-field"><label>Contact</label><input value={form.contact||''} onChange={e=>setForm(f=>({...f,contact:e.target.value}))}/></div><div className="px-field"><label>Notes / next decision</label><textarea value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></div><div className="px-field"><label>Guidelines / source context</label><textarea style={{minHeight:180}} value={form.context||''} onChange={e=>setForm(f=>({...f,context:e.target.value}))} placeholder="Paste only source material you want drafting and fit assessment to rely on."/></div></div><div className="px-form-actions"><Button variant="secondary" onClick={()=>setDrawer(null)}>Cancel</Button><Button onClick={save} disabled={busy}>{busy?'Saving…':'Save pursuit'}</Button></div></div></div>}
  </div>;
}
