import { useCallback, useEffect, useState } from 'react';
import { Button, EmptyState, Icon, LoadingRows, PageHeader, Panel, Pill, StateBanner } from '../components/ProductUI';

const copy={
  'tuku-core':'Identity authority for JakeOS and Momentum.',estate:'Product usage, growth, orders and earnings from Tuku Core.','local-ai':'Private estate-aware intelligence for Ask Jake and command-center analysis.','openai-errands':'Remote errands with web research, governed tools, budgets, evidence and approval gates.','google-workspace':'Gmail and Drive context/actions for governed errands after Google consent.','github-errands':'Repository read/write capability for approved software errands.','ops-executor':'Separately isolated production-action executor; JakeOS itself remains host read-only.','jakeos-mcp':'Scoped MCP boundary for approved ChatGPT/agent clients.',groq:'Voice memo transcription.',resend:'Email delivery for alerts and scheduled briefs.',telegram:'Telegram alert delivery.',sms:'Protected transaction ingestion for personal finance.'
};
const icon={identity:'users',data:'estate',calendar:'calendar',ai:'spark',alerts:'bell',finance:'money'};
export default function Integrations(){
  const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/integrations/status');if(!r.ok)throw new Error('Integration status could not be loaded.');const d=await r.json();setItems(d.integrations||[]);}catch(e){setError(e.message);}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search),result=params.get('google');if(!result)return;if(result==='connected')setNotice('Google Calendar connected. JakeOS can now read commitments and write scheduled work blocks.');if(result==='denied')setError('Google Calendar connection was cancelled. Nothing was changed.');if(result==='error')setError('Google Calendar could not be connected. Try again and confirm the Google permissions.');params.delete('google');const query=params.toString();window.history.replaceState(null,'',`${window.location.pathname}${query?`?${query}`:''}${window.location.hash}`);},[]);
  const calendar=items.find(x=>x.id==='google-calendar'),others=items.filter(x=>x.id!=='google-calendar');
  const connected=items.filter(x=>x.status==='connected'||x.configured&&x.status==='available').length,action=items.filter(x=>!x.configured||x.status==='action_required').length;
  const connectGoogle=async()=>{setBusy('connect');setError('');try{const r=await fetch('/api/gcal/auth-url'),d=await r.json().catch(()=>({}));if(!r.ok||!d.url)throw new Error(d.error||'Google Calendar connection could not start.');window.location.assign(d.url);}catch(e){setError(e.message);setBusy('');}};
  const syncGoogle=async()=>{setBusy('sync');setError('');setNotice('');try{const r=await fetch('/api/gcal/sync',{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Google Calendar sync failed.');setNotice(`Google Calendar synced${Number.isFinite(Number(d.count))?` · ${Number(d.count)} events imported`:''}.`);await load();}catch(e){setError(e.message);}setBusy('');};
  const disconnectGoogle=async()=>{if(!window.confirm('Disconnect Google Calendar from JakeOS? Existing JakeOS data will remain.'))return;setBusy('disconnect');setError('');setNotice('');try{const r=await fetch('/api/gcal/disconnect',{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Google Calendar could not be disconnected.');setNotice('Google Calendar disconnected from JakeOS.');await load();}catch(e){setError(e.message);}setBusy('');};
  return <div className="module"><PageHeader eyebrow="System" title="Integrations" subtitle="Connect the services JakeOS is allowed to use and see their real status." actions={<Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button>}/>{error&&<StateBanner tone="danger" title="Integration needs attention">{error}</StateBanner>}
    {notice&&<StateBanner tone="success" title="Google Calendar">{notice}</StateBanner>}
    <div className="px-metrics"><div className="px-metric px-metric--success"><div className="px-metric-value">{connected}</div><div className="px-metric-label">Connected / available</div><div className="px-metric-helper">Usable by JakeOS now</div></div><div className="px-metric px-metric--warning"><div className="px-metric-value">{action}</div><div className="px-metric-label">Action required</div><div className="px-metric-helper">Needs credentials or setup</div></div><div className="px-metric"><div className="px-metric-value">{items.length}</div><div className="px-metric-label">Tracked services</div><div className="px-metric-helper">Backend capability map</div></div><div className="px-metric"><div className="px-metric-value">1</div><div className="px-metric-label">Identity authority</div><div className="px-metric-helper">Tuku Core only</div></div></div>
    <Panel title="Google Calendar" subtitle="Connect your Google account once. JakeOS will use Calendar for commitments and scheduled work blocks.">
      {loading?<LoadingRows count={2}/>:!calendar?<EmptyState icon="calendar" title="Calendar status unavailable" body="JakeOS did not receive Google Calendar integration status."/>:<div className="px-panel" style={{boxShadow:'none'}}><div className="px-between"><div className="px-row"><div className="px-metric-icon" style={{margin:0}}><Icon name="calendar"/></div><div><div className="px-list-title">Google Calendar</div><div className="px-list-sub">{calendar.connected?(calendar.email||'Google account connected'):calendar.configured?'OAuth ready on this server':'OAuth client credentials are not configured'}</div></div></div><Pill tone={calendar.connected?'success':calendar.configured?'info':'warning'}>{calendar.connected?'Connected':calendar.configured?'Ready to connect':'Setup needed'}</Pill></div><div className="px-divider"/><div className="px-between" style={{alignItems:'flex-end',flexWrap:'wrap'}}><div><div className="px-kicker">What JakeOS gets</div><div className="px-muted" style={{fontSize:12,lineHeight:1.55,marginTop:6}}>{calendar.connected?'Read your calendar and create or update JakeOS time blocks.':'Google will ask you to approve calendar access. JakeOS stores the connection server-side.'}</div></div><div className="px-row" style={{flexWrap:'wrap'}}>{calendar.connected?<><Button variant="tonal" icon="refresh" disabled={!!busy} onClick={syncGoogle}>{busy==='sync'?'Syncing…':'Sync now'}</Button><Button variant="secondary" disabled={!!busy} onClick={connectGoogle}>Reconnect</Button><Button variant="ghost" disabled={!!busy} onClick={disconnectGoogle}>{busy==='disconnect'?'Disconnecting…':'Disconnect'}</Button></>:<Button icon="calendar" disabled={!calendar.configured||!!busy} onClick={connectGoogle}>{busy==='connect'?'Connecting…':'Connect Google Calendar'}</Button>}</div></div></div>}
    </Panel>
    <Panel title="Other connected capabilities" subtitle="JakeOS only labels a capability ready when its backend dependency is available.">{loading?<LoadingRows count={6}/>:others.length===0?<EmptyState icon="link" title="No other integrations returned" body="The backend did not report additional services."/>:<div className="px-grid-3">{others.map(item=>{const ready=item.configured&&item.status!=='action_required';return <div className="px-panel" key={item.id} style={{boxShadow:'none'}}><div className="px-between"><div className="px-metric-icon" style={{margin:0}}><Icon name={icon[item.category]||'link'}/></div><Pill tone={ready?'success':'warning'}>{ready?'Ready':'Setup needed'}</Pill></div><h3 style={{fontSize:14,margin:'14px 0 5px'}}>{item.name}</h3><p className="px-muted" style={{fontSize:12,lineHeight:1.5,minHeight:54}}>{copy[item.id]||item.detail||'JakeOS integration.'}</p>{!ready&&<div className="px-kicker">Configure on the JakeOS server to activate.</div>}</div>})}</div>}</Panel>
  </div>;
}
