import { useCallback, useEffect, useState } from 'react';
import { Button, EmptyState, Icon, LoadingRows, PageHeader, Panel, Pill, StateBanner } from '../components/ProductUI';

const copy={
  'tuku-core':'Identity authority for JakeOS and Momentum.',estate:'Product usage, growth, orders and earnings from Tuku Core.','google-calendar':'Server-side calendar sync for commitments and day planning.',anthropic:'Context-aware drafting and command-center analysis.',groq:'Voice memo transcription.',resend:'Email delivery for alerts and scheduled briefs.',telegram:'Telegram alert delivery.',sms:'Protected transaction ingestion for personal finance.'
};
const icon={identity:'users',data:'estate',calendar:'calendar',ai:'spark',alerts:'bell',finance:'money'};
export default function Integrations(){
  const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/integrations/status');if(!r.ok)throw new Error('Integration status could not be loaded.');const d=await r.json();setItems(d.integrations||[]);}catch(e){setError(e.message);}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const connected=items.filter(x=>x.status==='connected'||x.configured&&x.status==='available').length,action=items.filter(x=>!x.configured||x.status==='action_required').length;
  return <div className="module"><PageHeader eyebrow="System" title="Integrations" subtitle="A truthful view of what JakeOS can use now and what still needs account-side credentials." actions={<Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button>}/>{error&&<StateBanner tone="danger" title="Integration status unavailable">{error}</StateBanner>}
    <div className="px-metrics"><div className="px-metric px-metric--success"><div className="px-metric-value">{connected}</div><div className="px-metric-label">Connected / available</div><div className="px-metric-helper">Usable by JakeOS now</div></div><div className="px-metric px-metric--warning"><div className="px-metric-value">{action}</div><div className="px-metric-label">Action required</div><div className="px-metric-helper">Needs credentials or setup</div></div><div className="px-metric"><div className="px-metric-value">{items.length}</div><div className="px-metric-label">Tracked services</div><div className="px-metric-helper">Backend capability map</div></div><div className="px-metric"><div className="px-metric-value">1</div><div className="px-metric-label">Identity authority</div><div className="px-metric-helper">Tuku Core only</div></div></div>
    <Panel title="Connected capabilities" subtitle="JakeOS no longer labels a feature as live merely because a screen exists.">{loading?<LoadingRows count={6}/>:items.length===0?<EmptyState icon="link" title="No integration status returned" body="The backend did not report any configured services."/>:<div className="px-grid-3">{items.map(item=>{const ready=item.configured&&item.status!=='action_required';return <div className="px-panel" key={item.id} style={{boxShadow:'none'}}><div className="px-between"><div className="px-metric-icon" style={{margin:0}}><Icon name={icon[item.category]||'link'}/></div><Pill tone={ready?'success':'warning'}>{ready?'Ready':'Setup needed'}</Pill></div><h3 style={{fontSize:14,margin:'14px 0 5px'}}>{item.name}</h3><p className="px-muted" style={{fontSize:12,lineHeight:1.5,minHeight:54}}>{copy[item.id]||item.detail||'JakeOS integration.'}</p>{item.id==='google-calendar'&&item.configured&&<Button variant="tonal" onClick={()=>window.location.assign('/auth/google')}>Connect Google</Button>}{!ready&&<div className="px-kicker">Configure on the JakeOS server to activate.</div>}</div>})}</div>}</Panel>
  </div>;
}
