import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, LoadingRows, PageHeader, Panel, Pill, StateBanner, formatMoney, formatDate } from '../components/ProductUI';

const EMPTY={flow:'out',amount:'',party:'',category:'Other',provider:'Manual',note:'',currency:'UGX'};
const CATEGORIES=['Income','Housing','Food','Transport','Education','Utilities','Health','Accommodation','Cash Withdrawal','Other'];
export default function PersonalFinance({openAI}){
  const[transactions,setTransactions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState(EMPTY),[adding,setAdding]=useState(false),[filter,setFilter]=useState('all'),[webhook,setWebhook]=useState({configured:false,url:null});
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,b]=await Promise.all([fetch('/api/sms/transactions'),fetch('/api/sms/webhook-info')]);const[ta,wb]=await Promise.all([a.json(),b.json()]);setTransactions(ta.transactions||[]);setWebhook(wb||{});}catch(e){setError('Personal finance data could not be loaded.');}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const txns=transactions.filter(x=>x.type==='transaction'),visible=filter==='all'?txns:txns.filter(x=>x.flow===filter||x.category===filter);
  const totalIn=useMemo(()=>txns.filter(x=>x.flow==='in').reduce((s,x)=>s+Number(x.amount||0),0),[txns]),totalOut=useMemo(()=>txns.filter(x=>x.flow==='out').reduce((s,x)=>s+Number(x.amount||0),0),[txns]);
  const add=async()=>{if(!form.amount||!form.party.trim())return;setAdding(true);const r=await fetch('/api/personal-finance/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,amount:Number(form.amount)})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Transaction could not be saved.');else{setForm(EMPTY);await load();}setAdding(false);};
  const remove=async id=>{if(!confirm('Delete this transaction?'))return;await fetch(`/api/sms/transactions/${encodeURIComponent(id)}`,{method:'DELETE'});await load();};
  const note=async(tx,value)=>{await fetch(`/api/sms/transactions/${encodeURIComponent(tx.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:value,category:tx.category})});await load();};
  const cats=useMemo(()=>Object.entries(txns.reduce((m,x)=>{const k=x.category||'Other';m[k]=(m[k]||0)+(x.flow==='out'?Number(x.amount||0):0);return m;},{})).sort((a,b)=>b[1]-a[1]),[txns]);
  return <div className="module"><PageHeader eyebrow="Personal money" title="Personal finance" subtitle="A private transaction ledger fed by protected SMS ingestion or explicit manual entries." actions={<><Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button><Button variant="tonal" icon="spark" onClick={()=>openAI(`Personal finance live totals: received ${totalIn} UGX, spent ${totalOut} UGX, net ${totalIn-totalOut} UGX across ${txns.length} transactions. Identify spending patterns and decisions without inventing missing income or balances.`)}>Review</Button></>}/>{error&&<StateBanner tone="danger" title="Personal finance needs attention">{error}</StateBanner>}
    <div className="px-metrics"><div className="px-metric px-metric--success"><div className="px-metric-value">{formatMoney(totalIn,'UGX')}</div><div className="px-metric-label">Received</div><div className="px-metric-helper">Recorded inflows</div></div><div className="px-metric px-metric--danger"><div className="px-metric-value">{formatMoney(totalOut,'UGX')}</div><div className="px-metric-label">Spent / sent</div><div className="px-metric-helper">Recorded outflows</div></div><div className="px-metric"><div className="px-metric-value">{formatMoney(totalIn-totalOut,'UGX')}</div><div className="px-metric-label">Net recorded flow</div><div className="px-metric-helper">Not an account balance</div></div><div className="px-metric"><div className="px-metric-value">{txns.length}</div><div className="px-metric-label">Transactions</div><div className="px-metric-helper">Parsed + manual</div></div></div>
    {webhook.configured?<StateBanner tone="success" title="Protected SMS ingestion is configured">Your server has a private webhook secret. JakeOS does not display that secret in the UI.</StateBanner>:<StateBanner tone="info" title="SMS ingestion is not configured">Manual entry is available. Add a protected webhook secret on the server before forwarding bank or mobile-money SMS.</StateBanner>}
    <div className="px-grid-2"><Panel title="Transactions" subtitle="Filter by flow or category. Manual entries are stored directly—not simulated through the SMS webhook." action={<div className="px-row"><select className="px-input" value={filter} onChange={e=>setFilter(e.target.value)} style={{width:150}}><option value="all">All</option><option value="in">Received</option><option value="out">Spent</option>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></div>}>{loading?<LoadingRows count={6}/>:visible.length===0?<EmptyState icon="money" title="No transactions in this view" body="Add a manual transaction or configure SMS ingestion."/>:<div className="px-list">{visible.map(tx=><div className="px-list-row" key={tx.id}><div className="px-list-main"><div className="px-list-title">{tx.party||tx.provider||'Transaction'}</div><div className="px-list-sub">{tx.category||'Other'} · {tx.provider||'Unknown'} · {formatDate(tx.timestamp)}</div>{tx.note&&<div className="px-list-sub">{tx.note}</div>}</div><div style={{textAlign:'right'}}><div style={{fontWeight:750,color:tx.flow==='in'?'var(--px-success)':'var(--px-text)'}}>{tx.flow==='in'?'+':'−'} {formatMoney(tx.amount,tx.currency||'UGX')}</div><div className="px-row" style={{justifyContent:'flex-end',marginTop:4}}><button className="px-icon-button" title="Add note" onClick={()=>{const v=prompt('Transaction note',tx.note||'');if(v!==null)note(tx,v)}}>✎</button><button className="px-icon-button" title="Delete" onClick={()=>remove(tx.id)}>×</button></div></div></div>)}</div>}</Panel>
      <div className="px-stack"><Panel title="Add transaction" subtitle="For cash, transfers or records that do not arrive through SMS."><div className="px-stack"><div className="px-form-grid"><div className="px-field"><label>Flow</label><select value={form.flow} onChange={e=>setForm(f=>({...f,flow:e.target.value,category:e.target.value==='in'?'Income':f.category}))}><option value="in">Received</option><option value="out">Spent / sent</option></select></div><div className="px-field"><label>Amount</label><input type="number" min="0" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></div></div><div className="px-field"><label>Party</label><input value={form.party} onChange={e=>setForm(f=>({...f,party:e.target.value}))} placeholder="Person, merchant or source"/></div><div className="px-form-grid"><div className="px-field"><label>Category</label><select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Provider</label><input value={form.provider} onChange={e=>setForm(f=>({...f,provider:e.target.value}))} placeholder="MTN MoMo, Airtel, bank, cash…"/></div></div><div className="px-field"><label>Note</label><input value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))}/></div><Button onClick={add} disabled={adding}>{adding?'Saving…':'Save transaction'}</Button></div></Panel><Panel title="Spending by category" subtitle="Recorded outflows only.">{cats.length?<div className="px-list">{cats.slice(0,8).map(([cat,value])=><div className="px-list-row" key={cat}><div className="px-list-main"><div className="px-list-title">{cat}</div></div><strong>{formatMoney(value,'UGX')}</strong></div>)}</div>:<EmptyState icon="money" title="No spending data" body="Category patterns will appear as outflows are recorded."/>}</Panel></div></div>
  </div>;
}
