import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, LoadingRows, PageHeader, Pill, StateBanner, formatMoney, relativeDate } from '../components/ProductUI';

const STAGES=['Prospect','Applied','In Delivery','Active Partner','Closed','Lost'];
const ACTIVE_STAGES=new Set(['Prospect','Applied','In Delivery','Active Partner']);
const TYPES=['Consulting','Program','Partnership','Systems','Training','Academic','Other'];
const EMPTY={name:'',org:'',valueUSD:'',stage:'Prospect',type:'Consulting',deadline:'',contact:'',notes:''};
const tone=s=>s==='In Delivery'||s==='Active Partner'?'success':s==='Applied'?'warning':s==='Lost'?'danger':'neutral';

export default function Pipeline({openAI}){
  const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState(null),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/pipeline');if(!r.ok)throw new Error('Pipeline could not be loaded.');const d=await r.json();setItems(d.pipeline||[]);}catch(e){setError(e.message);}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const active=items.filter(x=>ACTIVE_STAGES.has(x.stage)),inDelivery=items.filter(x=>x.stage==='In Delivery'),applied=items.filter(x=>x.stage==='Applied');
  const totalActive=active.reduce((s,x)=>s+Number(x.valueUSD||x.value_usd||0),0),deliveryValue=inDelivery.reduce((s,x)=>s+Number(x.valueUSD||0),0),appliedValue=applied.reduce((s,x)=>s+Number(x.valueUSD||0),0);
  const dueSoon=useMemo(()=>active.filter(x=>x.deadline&&new Date(x.deadline)<=new Date(Date.now()+14*86400000)).length,[items]);
  const edit=item=>{setForm({...EMPTY,...item,valueUSD:item.valueUSD??item.value_usd??0,deadline:item.deadline?String(item.deadline).slice(0,10):''});setDrawer(item.id);};
  const create=()=>{setForm(EMPTY);setDrawer('new');};
  const save=async()=>{if(!form.name.trim()||!form.org.trim())return;setSaving(true);const body={...form,valueUSD:Number(form.valueUSD)||0,deadline:form.deadline||null};const r=await fetch(drawer==='new'?'/api/pipeline':`/api/pipeline/${encodeURIComponent(drawer)}`,{method:drawer==='new'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not save pipeline item.');else{setDrawer(null);setForm(EMPTY);await load();}setSaving(false);};
  const move=async(item,dir)=>{const i=STAGES.indexOf(item.stage),next=STAGES[Math.max(0,Math.min(STAGES.length-1,i+dir))];if(next===item.stage)return;await fetch(`/api/pipeline/${encodeURIComponent(item.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage:next})});await load();};
  const remove=async item=>{if(!confirm(`Remove ${item.name} from the pipeline?`))return;await fetch(`/api/pipeline/${encodeURIComponent(item.id)}`,{method:'DELETE'});await load();};
  return <div className="module">
    <PageHeader eyebrow="Business development" title="Pipeline" subtitle="Track live pursuits from first conversation through delivery, partnership or closure." actions={<><Button variant="secondary" icon="spark" onClick={()=>openAI(`Pipeline: ${active.length} active pursuits worth ${formatMoney(totalActive,'USD')}. ${inDelivery.length} in delivery, ${applied.length} applied, ${dueSoon} deadlines in 14 days. Identify the three commercial actions with highest leverage.`)}>Review</Button><Button icon="plus" onClick={create}>Add pursuit</Button></>}/>
    {error&&<StateBanner tone="danger" title="Pipeline needs attention">{error}</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{active.length}</div><div className="px-metric-label">Active pursuits</div><div className="px-metric-helper">{formatMoney(totalActive,'USD')} potential</div></div><div className="px-metric px-metric--success"><div className="px-metric-value">{formatMoney(deliveryValue,'USD')}</div><div className="px-metric-label">In delivery</div><div className="px-metric-helper">Current contracted/delivery value</div></div><div className="px-metric px-metric--warning"><div className="px-metric-value">{formatMoney(appliedValue,'USD')}</div><div className="px-metric-label">Applied</div><div className="px-metric-helper">Waiting on decisions</div></div><div className={`px-metric ${dueSoon?'px-metric--warning':''}`}><div className="px-metric-value">{dueSoon}</div><div className="px-metric-label">Deadlines / 14d</div><div className="px-metric-helper">Requires follow-through</div></div></div>
    {loading?<LoadingRows count={6}/>:items.length===0?<EmptyState icon="target" title="Pipeline is empty" body="Add consulting, programme, partnership, systems or training pursuits. JakeOS will surface deadlines in the command center." action={<Button variant="tonal" onClick={create}>Add first pursuit</Button>}/>:<div className="pipeline-kanban">{STAGES.filter(s=>s!=='Lost').map(stage=>{const rows=items.filter(x=>x.stage===stage);return <section className="kanban-col" key={stage}><div className="kanban-col-header"><Pill tone={tone(stage)}>{stage}</Pill><span className="kanban-count">{rows.length}</span></div><div className="kanban-items">{rows.length===0?<div className="px-empty" style={{padding:'24px 8px'}}><span className="px-kicker">No items</span></div>:rows.map(item=><article className="kanban-card" key={item.id} onClick={()=>edit(item)}><div className="kanban-card-org">{item.org}</div><div className="kanban-card-name">{item.name}</div>{Number(item.valueUSD||0)>0&&<div className="kanban-card-value">{formatMoney(item.valueUSD,'USD')}</div>}{item.deadline&&<div className="kanban-card-deadline">{relativeDate(item.deadline)} · {String(item.deadline).slice(0,10)}</div>}{item.notes&&<div className="kanban-card-notes">{item.notes}</div>}<div className="px-between" style={{marginTop:10}}><Pill>{item.type}</Pill><div className="px-row"><button className="px-icon-button" onClick={e=>{e.stopPropagation();move(item,-1)}} title="Move back">←</button><button className="px-icon-button" onClick={e=>{e.stopPropagation();move(item,1)}} title="Advance">→</button></div></div></article>)}</div></section>})}</div>}
    {drawer&&<div className="px-drawer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><div className="px-drawer-card"><PageHeader eyebrow={drawer==='new'?'New pursuit':'Edit pursuit'} title={drawer==='new'?'Add to pipeline':form.name||'Pipeline item'} subtitle="Keep the next commercial decision visible: stage, deadline, value and who you need to move." actions={<button className="px-icon-button" onClick={()=>setDrawer(null)}>×</button>}/><div className="px-stack"><div className="px-form-grid"><div className="px-field"><label>Name</label><input autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></div><div className="px-field"><label>Organisation</label><input value={form.org} onChange={e=>setForm(f=>({...f,org:e.target.value}))}/></div></div><div className="px-form-grid"><div className="px-field"><label>Stage</label><select value={form.stage} onChange={e=>setForm(f=>({...f,stage:e.target.value}))}>{STAGES.map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Type</label><select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="px-form-grid"><div className="px-field"><label>Value (USD)</label><input type="number" min="0" value={form.valueUSD} onChange={e=>setForm(f=>({...f,valueUSD:e.target.value}))}/></div><div className="px-field"><label>Deadline</label><input type="date" value={form.deadline||''} onChange={e=>setForm(f=>({...f,deadline:e.target.value}))}/></div></div><div className="px-field"><label>Primary contact</label><input value={form.contact||''} onChange={e=>setForm(f=>({...f,contact:e.target.value}))}/></div><div className="px-field"><label>Notes / next move</label><textarea value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></div></div><div className="px-form-actions">{drawer!=='new'&&<Button variant="danger" onClick={()=>remove(form)}>Remove</Button>}<span style={{flex:1}}/><Button variant="secondary" onClick={()=>setDrawer(null)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving?'Saving…':'Save'}</Button></div></div></div>}
  </div>;
}
