import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, EmptyState, LoadingRows, PageHeader, Panel, Pill, StateBanner } from '../components/ProductUI';

const LINKS={radar:'https://radar.tukutuku.org',units:'https://units.tukutuku.org',traffiq:'https://traffiq.tukutuku.org',ecitaa:'https://ecitaa.tukutuku.org',tukuiq:'https://tukuiq.tukutuku.org',kela:'https://kela.tukutuku.org',nena:'https://nena.tukutuku.org',lendflow:'https://lendflow.tukutuku.org',impactos:'https://impactos.tukutuku.org'};
export default function Platforms({openAI}){
  const[state,setState]=useState({loading:true,data:null,error:''});
  const load=useCallback(async(force=false)=>{setState(s=>({...s,loading:!s.data,error:''}));try{const r=await fetch(`/api/estate${force?'?refresh=1':''}`),d=await r.json();if(!r.ok&&!d.snapshot)throw new Error(d.error||'Portfolio data unavailable');setState({loading:false,data:d,error:d.error||''});}catch(e){setState(s=>({...s,loading:false,error:e.message}))}},[]);useEffect(()=>{load();},[load]);
  const products=useMemo(()=>[...(state.data?.snapshot?.products||[])].sort((a,b)=>Number(b.activeUsers7d)-Number(a.activeUsers7d)),[state.data]);
  const active=products.filter(x=>Number(x.activeUsers7d)>0),growing=products.filter(x=>Number(x.growth7dPercent)>0);
  return <div className="module"><PageHeader eyebrow="Product portfolio" title="Platforms" subtitle="A live product-health view derived from Tuku Estate telemetry—not manually typed vanity metrics." actions={<><Button variant="secondary" icon="refresh" onClick={()=>load(true)}>Refresh</Button><Button variant="tonal" icon="spark" onClick={()=>openAI(`Tuku product portfolio live metrics: ${products.map(p=>`${p.name}: ${p.activeUsers7d} active users in 7 days, ${p.growth7dPercent}% growth`).join('; ')}. Identify where to focus product attention without inventing revenue or engagement not shown.`)}>Review portfolio</Button></>}/>{state.error&&<StateBanner tone={state.data?.snapshot?'warning':'danger'} title="Portfolio data needs attention">{state.error}</StateBanner>}{state.data?.stale&&<StateBanner tone="warning" title="Showing cached product metrics">The Estate feed is stale; product activity below is the last successful snapshot.</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{products.length}</div><div className="px-metric-label">Estate products</div><div className="px-metric-helper">Reported by Tuku Core</div></div><div className="px-metric px-metric--success"><div className="px-metric-value">{active.length}</div><div className="px-metric-label">Active / 7d</div><div className="px-metric-helper">At least one observed user</div></div><div className="px-metric"><div className="px-metric-value">{growing.length}</div><div className="px-metric-label">Positive growth</div><div className="px-metric-helper">Vs preceding 7 days</div></div><div className="px-metric"><div className="px-metric-value">{products.reduce((s,p)=>s+Number(p.activeUsers7d||0),0)}</div><div className="px-metric-label">Product-user activity</div><div className="px-metric-helper">Sum across product windows</div></div></div>
    <Panel title="Portfolio" subtitle="Use product activity to decide where to investigate, support or stop spending attention.">{state.loading&&!products.length?<LoadingRows count={7}/>:products.length===0?<EmptyState icon="grid" title="No estate products reported" body="Platforms will populate automatically from Tuku Core telemetry."/>:<div className="px-grid-3">{products.map(p=><div key={p.code} className="px-panel" style={{boxShadow:'none'}}><div className="px-between"><div><div className="px-list-title">{p.name}</div><div className="px-list-sub">{p.code}</div></div><Pill tone={Number(p.activeUsers7d)>0?'success':'neutral'}>{Number(p.activeUsers7d)>0?'Active':'Quiet'}</Pill></div><div className="px-grid-3" style={{marginTop:16}}><div><div className="px-metric-value" style={{fontSize:20}}>{p.activeUsers24h||0}</div><div className="px-kicker">24h</div></div><div><div className="px-metric-value" style={{fontSize:20}}>{p.activeUsers7d||0}</div><div className="px-kicker">7d</div></div><div><div className="px-metric-value" style={{fontSize:20}}>{p.activeUsers30d||0}</div><div className="px-kicker">30d</div></div></div><div className="px-between" style={{marginTop:14}}><Pill tone={Number(p.growth7dPercent)>0?'success':Number(p.growth7dPercent)<0?'danger':'neutral'}>{Number(p.growth7dPercent||0)>0?'+':''}{Number(p.growth7dPercent||0).toFixed(1)}% growth</Pill>{LINKS[p.code]&&<Button variant="ghost" onClick={()=>window.open(LINKS[p.code],'_blank','noopener')}>Open</Button>}</div></div>)}</div>}</Panel>
  </div>;
}
