import { useCallback, useEffect, useMemo, useState } from 'react';
import { askClaude } from '../api/claude';
import { Button, EmptyState, LoadingRows, PageHeader, Panel, Pill, StateBanner, formatDate } from '../components/ProductUI';

const TYPES=['Consulting Proposal','Grant Application','Partnership MOU','Service Agreement','Project Brief'];
const EMPTY={title:'',type:'Consulting Proposal',client:'',value:'',dealId:'',content:'',status:'Draft'};
const tone=s=>s==='Accepted'?'success':s==='Sent'?'info':s==='Rejected'?'danger':'neutral';

export default function Proposals(){
  const[proposals,setProposals]=useState([]),[pipeline,setPipeline]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState(null),[form,setForm]=useState(EMPTY),[busy,setBusy]=useState(false),[aiReady,setAiReady]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const[a,b,c]=await Promise.all([fetch('/api/proposals'),fetch('/api/pipeline'),fetch('/api/integrations/status')]);const[pa,pi,ci]=await Promise.all([a.json(),b.json(),c.json()]);setProposals(pa.proposals||[]);setPipeline(pi.pipeline||[]);setAiReady((ci.integrations||[]).find(x=>x.id==='anthropic')?.configured===true);}catch(e){setError('Proposals could not be loaded.');}setLoading(false);},[]);useEffect(()=>{load();},[load]);
  const current=proposals.find(x=>x.id===selected)||null;
  const stats=useMemo(()=>({draft:proposals.filter(x=>x.status==='Draft').length,sent:proposals.filter(x=>x.status==='Sent').length,accepted:proposals.filter(x=>x.status==='Accepted').length}),[proposals]);
  const openNew=()=>{setForm(EMPTY);setDrawer('new');};const edit=p=>{setForm({...EMPTY,...p,dealId:p.deal_id||p.dealId||''});setDrawer(p.id);};
  const generate=async()=>{if(!form.title.trim())return;setBusy(true);const deal=pipeline.find(x=>x.id===form.dealId);const context=deal?`Proposal title: ${form.title}. Type: ${form.type}. Client: ${deal.org}. Pursuit: ${deal.name}. Stage: ${deal.stage}. Value: ${deal.valueUSD||0} USD. Notes: ${deal.notes||''}.`:`Proposal title: ${form.title}. Type: ${form.type}. Client: ${form.client||'not specified'}. Value: ${form.value||'not specified'}.`;const reply=await askClaude([{role:'user',content:'Draft a professional proposal structure and first draft. Use clear headings, scope, approach, deliverables, timeline, fees/value where known, assumptions and next step. Do not invent facts not supplied.'}],'proposals',context);setForm(f=>({...f,content:reply}));setBusy(false);};
  const save=async()=>{if(!form.title.trim())return;setBusy(true);const r=await fetch(drawer==='new'?'/api/proposals':`/api/proposals/${encodeURIComponent(drawer)}`,{method:drawer==='new'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Proposal could not be saved.');else{setDrawer(null);await load();setSelected(d.proposal?.id||selected);}setBusy(false);};
  const updateStatus=async(p,status)=>{await fetch(`/api/proposals/${encodeURIComponent(p.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await load();};
  const remove=async p=>{if(!confirm(`Delete ${p.title}?`))return;await fetch(`/api/proposals/${encodeURIComponent(p.id)}`,{method:'DELETE'});setSelected(null);await load();};
  const printProposal=p=>{const win=window.open('','_blank');if(!win)return;const safe=String(p.content||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])).replace(/^##? (.+)$/gm,'<h2>$1</h2>').replace(/\n/g,'<br>');win.document.write(`<html><head><title>${p.title}</title><style>body{font:16px/1.65 Georgia,serif;max-width:800px;margin:50px auto;padding:0 30px;color:#18201d}h1,h2{font-family:Arial,sans-serif}h2{margin-top:30px}</style></head><body><h1>${p.title}</h1><p><strong>${p.client||''}</strong> · ${p.type}</p>${safe}</body></html>`);win.document.close();win.print();};
  return <div className="module"><PageHeader eyebrow="Business development" title="Proposals" subtitle="Durable proposal drafts connected to live pipeline pursuits—not browser-local documents." actions={<Button icon="plus" onClick={openNew}>New proposal</Button>}/>{error&&<StateBanner tone="danger" title="Proposal data needs attention">{error}</StateBanner>}{!aiReady&&<StateBanner tone="info" title="AI drafting is not configured">You can create, edit, track and print proposals now. AI generation will activate when the server AI credential is added.</StateBanner>}
    <div className="px-metrics"><div className="px-metric"><div className="px-metric-value">{proposals.length}</div><div className="px-metric-label">Proposals</div><div className="px-metric-helper">Durable JakeOS records</div></div><div className="px-metric"><div className="px-metric-value">{stats.draft}</div><div className="px-metric-label">Draft</div><div className="px-metric-helper">Still being worked</div></div><div className="px-metric"><div className="px-metric-value">{stats.sent}</div><div className="px-metric-label">Sent</div><div className="px-metric-helper">Awaiting decision</div></div><div className="px-metric px-metric--success"><div className="px-metric-value">{stats.accepted}</div><div className="px-metric-label">Accepted</div><div className="px-metric-helper">Converted work</div></div></div>
    <div className="px-grid-2"><Panel title="Proposal library" subtitle="Open a draft to review its content and status.">{loading?<LoadingRows count={5}/>:proposals.length===0?<EmptyState icon="document" title="No proposals yet" body="Create one from a live pipeline pursuit or start a standalone document." action={<Button variant="tonal" onClick={openNew}>Create proposal</Button>}/>:<div className="px-list">{proposals.map(p=><button key={p.id} className="px-list-row" onClick={()=>setSelected(p.id)} style={{width:'100%',textAlign:'left',cursor:'pointer',borderColor:selected===p.id?'rgba(36,92,70,.35)':undefined}}><div className="px-list-main"><div className="px-list-title">{p.title}</div><div className="px-list-sub">{p.client||'No client'} · {p.type} · updated {formatDate(p.updated_at)}</div></div><Pill tone={tone(p.status)}>{p.status}</Pill></button>)}</div>}</Panel>
      <Panel title={current?.title||'Proposal detail'} subtitle={current?`${current.client||'No client'} · ${current.type}`:'Select a proposal from the library.'}>{current?<><div className="px-between" style={{marginBottom:14}}><Pill tone={tone(current.status)}>{current.status}</Pill><div className="px-row"><Button variant="ghost" onClick={()=>printProposal(current)}>Print / PDF</Button><Button variant="secondary" onClick={()=>edit(current)}>Edit</Button></div></div><div style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.65,maxHeight:'60vh',overflow:'auto',padding:'4px 2px'}}>{current.content||'No proposal content yet.'}</div><div className="px-form-actions" style={{justifyContent:'flex-start'}}>{current.status==='Draft'&&<Button variant="tonal" onClick={()=>updateStatus(current,'Sent')}>Mark sent</Button>}{current.status==='Sent'&&<><Button variant="tonal" onClick={()=>updateStatus(current,'Accepted')}>Accepted</Button><Button variant="danger" onClick={()=>updateStatus(current,'Rejected')}>Rejected</Button></>}<Button variant="ghost" onClick={()=>remove(current)}>Delete</Button></div></>:<EmptyState icon="document" title="Choose a proposal" body="The detail view keeps drafting, status and export actions in one place."/>}</Panel></div>
    {drawer&&<div className="px-drawer" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><div className="px-drawer-card"><PageHeader eyebrow="Proposal" title={drawer==='new'?'New proposal':'Edit proposal'} subtitle="Link to a pursuit where possible so context stays connected." actions={<button className="px-icon-button" onClick={()=>setDrawer(null)}>×</button>}/><div className="px-stack"><div className="px-field"><label>Title</label><input autoFocus value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div className="px-form-grid"><div className="px-field"><label>Type</label><select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></div><div className="px-field"><label>Pipeline pursuit</label><select value={form.dealId||''} onChange={e=>{const deal=pipeline.find(x=>x.id===e.target.value);setForm(f=>({...f,dealId:e.target.value,client:deal?.org||f.client,value:deal?.valueUSD?`$${Number(deal.valueUSD).toLocaleString()}`:f.value}))}}><option value="">Standalone</option>{pipeline.map(x=><option key={x.id} value={x.id}>{x.org} · {x.name}</option>)}</select></div></div><div className="px-form-grid"><div className="px-field"><label>Client</label><input value={form.client||''} onChange={e=>setForm(f=>({...f,client:e.target.value}))}/></div><div className="px-field"><label>Value</label><input value={form.value||''} onChange={e=>setForm(f=>({...f,value:e.target.value}))}/></div></div><div className="px-between"><div className="px-field" style={{minWidth:160}}><label>Status</label><select value={form.status||'Draft'} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{['Draft','Sent','Accepted','Rejected','Archived'].map(x=><option key={x}>{x}</option>)}</select></div><Button variant="tonal" icon="spark" disabled={!aiReady||busy} onClick={generate}>{busy?'Drafting…':'Draft with AI'}</Button></div><div className="px-field"><label>Content</label><textarea style={{minHeight:360}} value={form.content||''} onChange={e=>setForm(f=>({...f,content:e.target.value}))} placeholder="Write or paste the proposal here…"/></div></div><div className="px-form-actions"><Button variant="secondary" onClick={()=>setDrawer(null)}>Cancel</Button><Button onClick={save} disabled={busy}>{busy?'Saving…':'Save proposal'}</Button></div></div></div>}
  </div>;
}
