import { useEffect, useRef, useState } from 'react';
import { askClaude } from '../api/claude';
import { Button, EmptyState, Icon, PageHeader, Panel, Pill, StateBanner } from '../components/ProductUI';

export default function VoiceMemo(){
  const[status,setStatus]=useState('idle'),[seconds,setSeconds]=useState(0),[transcript,setTranscript]=useState(''),[parsed,setParsed]=useState(null),[error,setError]=useState(''),[services,setServices]=useState({groq:false,ai:false}),[selected,setSelected]=useState({});
  const recorder=useRef(null),chunks=useRef([]),timer=useRef(null);
  useEffect(()=>{fetch('/api/integrations/status').then(r=>r.json()).then(d=>{const x=d.integrations||[];setServices({groq:x.find(i=>i.id==='groq')?.configured===true,ai:x.find(i=>i.id==='anthropic')?.configured===true});}).catch(()=>{});return()=>{clearInterval(timer.current);recorder.current?.stream?.getTracks().forEach(t=>t.stop());};},[]);
  const enabled=services.groq&&services.ai;
  const parse=async text=>{if(!text.trim())return setStatus('idle');setStatus('parsing');const reply=await askClaude([{role:'user',content:`Extract actionable records from this transcript. Return ONLY JSON with this structure: {"tasks":[{"title":"","description":"","project_id":null,"priority":"medium","due_at":null}],"events":[{"title":"","date":"YYYY-MM-DD","time":"HH:MM","notes":""}],"contacts":[{"name":"","org":"","notes":""}],"deals":[{"name":"","org":"","notes":"","valueUSD":0}],"summary":""}. Do not invent dates, values, organisations or people. Use null/empty when absent. Transcript: ${JSON.stringify(text)}`}],'voice-memo',`Today is ${new Date().toISOString().slice(0,10)}.`);try{const cleaned=String(reply).replace(/```json?/g,'').replace(/```/g,'').trim();const data=JSON.parse(cleaned);setParsed(data);const s={};['tasks','events','contacts','deals'].forEach(type=>(data[type]||[]).forEach((_,i)=>s[`${type}-${i}`]=true));setSelected(s);setStatus('done');}catch{setError('The transcript was captured but JakeOS could not structure it safely. You can copy the transcript into Work instead.');setStatus('done');}};
  const transcribe=blob=>{setStatus('transcribing');const reader=new FileReader();reader.onload=async()=>{try{const r=await fetch('/api/groq/transcribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio:String(reader.result).split(',')[1],mimeType:blob.type||'audio/webm',filename:'momentum.webm'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Transcription failed');setTranscript(d.text||'');await parse(d.text||'');}catch(e){setError(e.message);setStatus('error');}};reader.readAsDataURL(blob);};
  const start=async()=>{if(!enabled)return;setError('');setTranscript('');setParsed(null);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),mr=new MediaRecorder(stream);chunks.current=[];mr.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);mr.onstop=()=>transcribe(new Blob(chunks.current,{type:mr.mimeType||'audio/webm'}));mr.start(250);recorder.current=mr;setSeconds(0);setStatus('recording');timer.current=setInterval(()=>setSeconds(s=>s+1),1000);}catch{setError('Microphone access was not granted.');setStatus('error');}};
  const stop=()=>{clearInterval(timer.current);const mr=recorder.current;if(!mr)return;mr.stop();mr.stream.getTracks().forEach(t=>t.stop());};
  const upload=e=>{const file=e.target.files?.[0];if(file&&enabled){setError('');transcribe(file);}};
  const addSelected=async()=>{if(!parsed)return;setStatus('saving');let n=0;for(const[type,items]of Object.entries({tasks:parsed.tasks||[],events:parsed.events||[],contacts:parsed.contacts||[],deals:parsed.deals||[]})){for(let i=0;i<items.length;i++){if(!selected[`${type}-${i}`])continue;const x=items[i];try{let url,body;if(type==='tasks'){url='/api/work/items';body={title:x.title||x.text,description:x.description||'',status:'inbox',priority:x.priority||'medium',due_at:x.due_at||null,source:'voice-memo'};}else if(type==='events'){url='/api/calendar/events';body={title:x.title,date:x.date,time:x.time||'',notes:x.notes||'',project:'Voice capture',type:'session'};}else if(type==='contacts'){url='/api/clients';body={id:`voice_contact_${Date.now()}_${i}`,name:x.name,org:x.org||'',notes:x.notes||'',type:'Contact',status:'Active'};}else{url='/api/pipeline';body={id:`voice_deal_${Date.now()}_${i}`,name:x.name,org:x.org||'',notes:x.notes||'',valueUSD:Number(x.valueUSD)||0,stage:'Prospect',type:'Other'};}const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok)n++;}catch{}}}setStatus('done');setError(n?`${n} selected item${n===1?'':'s'} added to JakeOS.`:'No items were added.');};
  const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
  return <div className="module"><PageHeader eyebrow="Capture" title="Voice capture" subtitle="Turn a short spoken memo into reviewable JakeOS tasks, events, contacts and pipeline items."/>{!enabled&&<StateBanner tone="warning" title="Voice intelligence is not configured">Recording-to-action requires both Groq transcription and the AI parser. Until those server credentials are added, use the Work capture box for reliable quick entry.</StateBanner>}{error&&<StateBanner tone={status==='error'?'danger':'info'} title={status==='error'?'Voice capture failed':'Voice capture'}>{error}</StateBanner>}
    <div className="px-grid-2"><Panel title="Record or upload" subtitle="Nothing is added automatically. You approve extracted records first."><div className="px-empty" style={{padding:'28px 10px'}}><div className="px-empty-icon"><Icon name="mic" size={22}/></div><h3>{status==='recording'?`Recording · ${fmt(seconds)}`:status==='transcribing'?'Transcribing audio…':status==='parsing'?'Structuring transcript…':'Capture a short memo'}</h3><p>Best for decisions, follow-ups and commitments you want to capture without typing.</p><div className="px-row" style={{justifyContent:'center',flexWrap:'wrap'}}>{status==='recording'?<Button variant="danger" onClick={stop}>Stop recording</Button>:<Button icon="mic" disabled={!enabled||['transcribing','parsing','saving'].includes(status)} onClick={start}>Start recording</Button>}<label className={`px-btn px-btn--secondary`} style={{opacity:enabled?1:.5,cursor:enabled?'pointer':'not-allowed'}}><Icon name="upload" size={16}/>Upload audio<input type="file" accept="audio/*" disabled={!enabled} onChange={upload} style={{display:'none'}}/></label></div></div>{transcript&&<><div className="px-divider"/><div className="px-list-title">Transcript</div><p className="px-muted" style={{fontSize:12,lineHeight:1.65,whiteSpace:'pre-wrap'}}>{transcript}</p></>}</Panel>
      <Panel title="Review extracted items" subtitle="Approve only records the transcript actually supports.">{parsed?<><p className="px-muted" style={{fontSize:12,lineHeight:1.55}}>{parsed.summary}</p>{['tasks','events','contacts','deals'].map(type=>(parsed[type]||[]).length?<div key={type} style={{marginTop:14}}><div className="px-eyebrow">{type}</div><div className="px-list">{parsed[type].map((x,i)=><label className="px-list-row" key={`${type}-${i}`} style={{cursor:'pointer'}}><input type="checkbox" checked={!!selected[`${type}-${i}`]} onChange={e=>setSelected(s=>({...s,[`${type}-${i}`]:e.target.checked}))}/><div className="px-list-main"><div className="px-list-title">{x.title||x.text||x.name}</div><div className="px-list-sub">{x.org||x.date||x.description||x.notes||'Review before adding'}</div></div>{x.priority&&<Pill>{x.priority}</Pill>}</label>)}</div></div>:null)}<div className="px-form-actions"><Button onClick={addSelected} disabled={status==='saving'}>{status==='saving'?'Adding…':'Add selected to JakeOS'}</Button></div></>:<EmptyState icon="mic" title="Nothing to review yet" body={enabled?'Record or upload audio; JakeOS will transcribe and structure it for approval.':'Configure Groq and AI credentials, or use Work for quick typed capture.'}/>}</Panel></div>
  </div>;
}
