'use strict';
const db=require('./db');
const SCOPES=['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/userinfo.email'].join(' ');
let tokenStore={accessToken:null,accessTokenExpiry:0,refreshToken:process.env.GOOGLE_REFRESH_TOKEN||null,userEmail:process.env.GOOGLE_USER_EMAIL||null};
async function hydrate(){try{const[rt,em]=await Promise.all([db.get('settings',{eq:{key:'google_refresh_token'}}),db.get('settings',{eq:{key:'google_user_email'}})]);if(rt?.value)tokenStore.refreshToken=rt.value;if(em?.value)tokenStore.userEmail=em.value;}catch(e){console.warn('[GCal] token hydrate failed:',e.message);}return getStatus();}
function isConfigured(){return !!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET);}function isConnected(){return !!tokenStore.refreshToken;}
function buildAuthUrl(redirectUri){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirectUri||process.env.GOOGLE_REDIRECT_URI,response_type:'code',scope:SCOPES,access_type:'offline',prompt:'consent'});return `https://accounts.google.com/o/oauth2/v2/auth?${params}`;}
async function exchangeCode(code,redirectUri){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirectUri||process.env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})});const d=await r.json();if(d.error)throw new Error(d.error_description||d.error);tokenStore.accessToken=d.access_token;tokenStore.accessTokenExpiry=Date.now()+(d.expires_in-60)*1000;if(d.refresh_token)tokenStore.refreshToken=d.refresh_token;try{const me=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:`Bearer ${tokenStore.accessToken}`}});tokenStore.userEmail=(await me.json()).email||null;}catch{}if(tokenStore.refreshToken)await db.insert('settings',{key:'google_refresh_token',value:tokenStore.refreshToken,updated_at:new Date().toISOString()},true);if(tokenStore.userEmail)await db.insert('settings',{key:'google_user_email',value:tokenStore.userEmail,updated_at:new Date().toISOString()},true);return{accessToken:tokenStore.accessToken,refreshToken:tokenStore.refreshToken,email:tokenStore.userEmail};}
async function refreshAccessToken(){if(!tokenStore.refreshToken)throw new Error('No refresh token — reconnect Google Calendar');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:tokenStore.refreshToken,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,grant_type:'refresh_token'})});const d=await r.json();if(d.error)throw new Error(d.error_description||d.error);tokenStore.accessToken=d.access_token;tokenStore.accessTokenExpiry=Date.now()+(d.expires_in-60)*1000;return tokenStore.accessToken;}
async function getAccessToken(){if(tokenStore.accessToken&&Date.now()<tokenStore.accessTokenExpiry)return tokenStore.accessToken;return refreshAccessToken();}
async function getCalendars(){const token=await getAccessToken(),r=await fetch('https://www.googleapis.com/calendar/v3/users/me/calendarList',{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(d.error)throw new Error(d.error.message);return d.items||[];}
async function getEvents({calendarId='primary',days=60,maxResults=100}={}){const token=await getAccessToken(),params=new URLSearchParams({timeMin:new Date().toISOString(),timeMax:new Date(Date.now()+days*86400000).toISOString(),maxResults:String(maxResults),singleEvents:'true',orderBy:'startTime'}),r=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?${params}`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(d.error)throw new Error(d.error.message);return(d.items||[]).map(event=>({id:`gcal_${event.id}`,title:event.summary||'(No title)',date:(event.start?.dateTime||event.start?.date||'').slice(0,10),dateTime:event.start?.dateTime||null,endDate:(event.end?.dateTime||event.end?.date||'').slice(0,10),endDateTime:event.end?.dateTime||null,project:'Google Calendar',type:'gcal',gcalLink:event.htmlLink||null,location:event.location||null,desc:event.description||null,allDay:!event.start?.dateTime,done:false,source:'google',calendarId,colorId:event.colorId||null}));}
async function getAllEvents({days=60}={}){const calendars=await getCalendars(),out=[];for(const cal of calendars){if(cal.selected===false)continue;try{const events=await getEvents({calendarId:cal.id,days});out.push(...events.map(e=>({...e,calendarName:cal.summary,calendarColor:cal.backgroundColor})));}catch(e){console.warn(`[GCal] Could not fetch calendar ${cal.summary}:`,e.message);}}return out;}
function getStatus(){return{configured:isConfigured(),connected:isConnected(),email:tokenStore.userEmail,hasToken:!!tokenStore.accessToken,tokenValid:Date.now()<tokenStore.accessTokenExpiry};}
function disconnect(){tokenStore={accessToken:null,accessTokenExpiry:0,refreshToken:null,userEmail:null};db.insert('settings',{key:'google_refresh_token',value:'',updated_at:new Date().toISOString()},true).catch(()=>{});db.insert('settings',{key:'google_user_email',value:'',updated_at:new Date().toISOString()},true).catch(()=>{});}
module.exports={hydrate,isConfigured,isConnected,buildAuthUrl,exchangeCode,getAccessToken,getCalendars,getEvents,getAllEvents,getStatus,disconnect,tokenStore};
