'use strict';
const crypto=require('crypto');
let certCache={expiresAt:0,certs:null};
function timingSafeStringEqual(a,b){const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
function parseJwt(token){const parts=String(token||'').split('.');if(parts.length!==3)throw new Error('Malformed token');const decode=value=>JSON.parse(Buffer.from(value.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8'));return{header:decode(parts[0]),payload:decode(parts[1]),signed:`${parts[0]}.${parts[1]}`,signature:Buffer.from(parts[2].replace(/-/g,'+').replace(/_/g,'/'),'base64')};}
async function firebaseCerts(){if(certCache.certs&&certCache.expiresAt>Date.now())return certCache.certs;const response=await fetch('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Firebase certificate lookup failed');const cacheControl=response.headers.get('cache-control')||'',maxAge=Number(cacheControl.match(/max-age=(\d+)/)?.[1]||3600);certCache={certs:await response.json(),expiresAt:Date.now()+Math.max(300,maxAge-60)*1000};return certCache.certs;}
async function verifyFirebaseIdToken(token,projectId){const{header,payload,signed,signature}=parseJwt(token);if(header.alg!=='RS256'||!header.kid)throw new Error('Unsupported Firebase token');const now=Math.floor(Date.now()/1000);if(payload.aud!==projectId)throw new Error('Wrong Firebase audience');if(payload.iss!==`https://securetoken.google.com/${projectId}`)throw new Error('Wrong Firebase issuer');if(!payload.sub||typeof payload.sub!=='string')throw new Error('Missing Firebase subject');if(Number(payload.exp||0)<=now)throw new Error('Firebase token expired');if(Number(payload.iat||now+1)>now+60)throw new Error('Firebase token issued in the future');const cert=(await firebaseCerts())[header.kid];if(!cert)throw new Error('Unknown Firebase signing key');const verifier=crypto.createVerify('RSA-SHA256');verifier.update(signed);verifier.end();if(!verifier.verify(cert,signature))throw new Error('Invalid Firebase signature');return payload;}
function csvEnv(name){return new Set(String(process.env[name]||'').split(',').map(v=>v.trim()).filter(Boolean));}
function momentumAuth(){return async(req,res,next)=>{const bearer=String(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1];if(!bearer)return res.status(401).json({error:'Momentum authentication required'});const projectId=process.env.MOMENTUM_FIREBASE_PROJECT_ID||process.env.FIREBASE_PROJECT_ID,fallback=process.env.MOMENTUM_API_TOKEN;try{if(projectId){const claims=await verifyFirebaseIdToken(bearer,projectId),allowedUids=csvEnv('MOMENTUM_ALLOWED_UIDS'),allowedEmails=csvEnv('MOMENTUM_ALLOWED_EMAILS');if(allowedUids.size&&!allowedUids.has(claims.sub))return res.status(403).json({error:'Momentum account is not allowed'});if(allowedEmails.size&&!allowedEmails.has(String(claims.email||'').toLowerCase()))return res.status(403).json({error:'Momentum account is not allowed'});req.momentumUser={uid:claims.sub,email:claims.email||null,name:claims.name||null,provider:'firebase'};return next();}if(fallback&&timingSafeStringEqual(bearer,fallback)){req.momentumUser={uid:'personal',email:null,name:'Jacob',provider:'token'};return next();}return res.status(503).json({error:'Momentum authentication is not configured'});}catch(error){return res.status(401).json({error:'Invalid Momentum session',detail:process.env.NODE_ENV==='development'?error.message:undefined});}};}
function ingestAuth(){return(req,res,next)=>{const configured=process.env.JAKEOS_INGEST_TOKEN||'',bearer=String(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1]||'';if(!configured||!timingSafeStringEqual(configured,bearer))return res.status(401).json({error:'Invalid ingest token'});next();};}
module.exports={momentumAuth,ingestAuth,verifyFirebaseIdToken};
