'use strict';
const db=require('./db');
async function commandCenterOverview(){const[taskCounts,projectRows,pipelineRows,invoiceRows,opportunityRows,briefRows,signals]=await Promise.all([
  db.query(`SELECT COUNT(*) FILTER(WHERE status NOT IN('done','cancelled'))::int AS open,COUNT(*) FILTER(WHERE status='inbox')::int AS inbox,COUNT(*) FILTER(WHERE status='doing')::int AS doing,COUNT(*) FILTER(WHERE status NOT IN('done','cancelled') AND due_at<NOW())::int AS overdue,COUNT(*) FILTER(WHERE status NOT IN('done','cancelled') AND(blocked=TRUE OR status='waiting'))::int AS blocked,COUNT(*) FILTER(WHERE status='done' AND completed_at>=date_trunc('week',NOW()))::int AS completed_this_week FROM work_items`),
  db.query(`SELECT p.id,p.name,p.emoji,p.status,p.priority,p.progress,COUNT(wi.id) FILTER(WHERE wi.status NOT IN('done','cancelled'))::int AS open_tasks,COUNT(wi.id) FILTER(WHERE wi.status NOT IN('done','cancelled') AND wi.due_at<NOW())::int AS overdue_tasks,COUNT(wi.id) FILTER(WHERE wi.status NOT IN('done','cancelled') AND(wi.blocked=TRUE OR wi.status='waiting'))::int AS blocked_tasks FROM projects p LEFT JOIN work_items wi ON wi.project_id=p.id GROUP BY p.id ORDER BY overdue_tasks DESC,blocked_tasks DESC,p.priority,p.name LIMIT 100`),
  db.query(`SELECT COUNT(*) FILTER(WHERE stage NOT IN('Closed','Lost','Delivered'))::int AS active,COALESCE(SUM(value_usd) FILTER(WHERE stage NOT IN('Closed','Lost','Delivered')),0)::numeric AS active_value_usd,COUNT(*) FILTER(WHERE deadline IS NOT NULL AND deadline ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' AND deadline::timestamptz BETWEEN NOW() AND NOW()+INTERVAL '14 days')::int AS deadlines_14d FROM pipeline`),
  db.query(`SELECT COUNT(*) FILTER(WHERE status IN('Sent','Overdue'))::int AS receivables,COALESCE(SUM(total) FILTER(WHERE status IN('Sent','Overdue')),0)::numeric AS receivables_value,COUNT(*) FILTER(WHERE status IN('Sent','Overdue') AND due_date IS NOT NULL AND due_date<>'' AND due_date::date<CURRENT_DATE)::int AS overdue_count,COALESCE(SUM(total) FILTER(WHERE status IN('Sent','Overdue') AND due_date IS NOT NULL AND due_date<>'' AND due_date::date<CURRENT_DATE),0)::numeric AS overdue_value FROM invoices`),
  db.query(`SELECT COUNT(*) FILTER(WHERE status NOT IN('Dismissed','Applied'))::int AS open,COUNT(*) FILTER(WHERE status NOT IN('Dismissed','Applied') AND relevance_score>=75)::int AS high_relevance,COUNT(*) FILTER(WHERE status NOT IN('Dismissed','Applied') AND deadline IS NOT NULL AND deadline ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' AND deadline::timestamptz BETWEEN NOW() AND NOW()+INTERVAL '14 days')::int AS deadlines_14d FROM opportunities`),
  db.query(`SELECT id,brief_date,title,summary,items,watchlist,created_at FROM research_briefs ORDER BY brief_date DESC LIMIT 1`),
  db.query(`SELECT id,signal_type,title,summary,severity,source,source_ref,action_url,due_at,metadata FROM attention_signals WHERE resolved=FALSE ORDER BY severity DESC,COALESCE(due_at,created_at) ASC LIMIT 12`)
]);return{generated_at:new Date().toISOString(),tasks:taskCounts.rows[0]||{},projects:projectRows.rows,pipeline:pipelineRows.rows[0]||{},invoices:invoiceRows.rows[0]||{},opportunities:opportunityRows.rows[0]||{},latest_research_brief:briefRows.rows[0]||null,attention_signals:signals.rows};}
module.exports={commandCenterOverview};
