'use strict';
const crypto=require('crypto');
const express=require('express');
const rateLimit=require('express-rate-limit');

const WEB_SESSION_COOKIE='jakeos_session';
const PKCE_COOKIE='jakeos_pkce';
const STATE_COOKIE='jakeos_state';
const RETURN_COOKIE='jakeos_return_to';
const tokenCache=new Map();

function coreInternalUrl(){return String(process.env.TUKU_CORE_INTERNAL_URL||process.env.TUKU_CORE_URL||'http://tuku-core-api:3000').replace(/\/$/,'');}
function corePublicUrl(){return String(process.env.TUKU_AUTH_PUBLIC_URL||'https://core.tukutuku.org').replace(/\/$/,'');}
function ownerIds(){return new Set(String(process.env.JAKEOS_ALLOWED_CORE_USER_IDS||'').split(',').map(v=>v.trim()).filter(Boolean));}
function ownerAllowed(coreUserId){const allowed=ownerIds();if(allowed.size===0)return process.env.NODE_ENV==='test';return allowed.has(String(coreUserId||''));}
function secureCookies(){return process.env.NODE_ENV==='production'||String(process.env.PUBLIC_URL||'').startsWith('https://');}
function cookieOptions(maxAge){return{httpOnly:true,secure:secureCookies(),sameSite:'lax',path:'/',...(maxAge?{maxAge}: {})};}
function parseCookies(req){const raw=String(req.headers.cookie||'');const out={};for(const part of raw.split(';')){const i=part.indexOf('=');if(i<0)continue;const k=part.slice(0,i).trim(),v=part.slice(i+1).trim();if(!k)continue;try{out[k]=decodeURIComponent(v);}catch{out[k]=v;}}return out;}
function safeReturnTo(value){const v=String(value||'/').trim();return v.startsWith('/')&&!v.startsWith('//')?v:'/';}
function b64(value){return Buffer.from(JSON.stringify(value)).toString('base64url');}
function sessionSecret(){return process.env.JAKEOS_SESSION_SECRET||(process.env.NODE_ENV==='test'?'ci-jakeos-session-secret':'');}
function unwrap(body){return body&&typeof body==='object'&&body.data&&typeof body.data==='object'?body.data:body;}
function coreError(body,fallback){const data=unwrap(body)||{};return data.message||data.error?.message||body?.message||body?.error?.message||fallback;}
function signLocalSession(identity,authorization){const secret=sessionSecret();if(!secret)throw new Error('JAKEOS_SESSION_SECRET is not configured');const now=Math.floor(Date.now()/1000),ttl=Math.max(900,Math.min(Number(process.env.JAKEOS_SESSION_TTL_SECONDS||43200),7*86400));const payload={iss:'jakeos',aud:'jakeos-web',sub:identity.coreUserId,email:identity.email||null,organization_id:authorization?.organizationId||null,roles:authorization?.organizationRoleCodes||[],permissions:authorization?.permissionCodes||[],iat:now,exp:now+ttl};const encoded=b64(payload),sig=crypto.createHmac('sha256',secret).update(encoded).digest('base64url');return{token:`${encoded}.${sig}`,payload,ttl};}
function verifyLocalSession(token){const secret=sessionSecret();if(!secret)throw new Error('JAKEOS_SESSION_SECRET is not configured');const[encoded,sig,...extra]=String(token||'').split('.');if(!encoded||!sig||extra.length)throw new Error('Malformed JakeOS session');const expected=crypto.createHmac('sha256',secret).update(encoded).digest(),actual=Buffer.from(sig,'base64url');if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))throw new Error('Invalid JakeOS session signature');const payload=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')),now=Math.floor(Date.now()/1000);if(payload.iss!=='jakeos'||payload.aud!=='jakeos-web'||!payload.sub)throw new Error('Invalid JakeOS session claims');if(Number(payload.exp||0)<=now)throw new Error('JakeOS session expired');if(!ownerAllowed(payload.sub))throw Object.assign(new Error('This Tuku identity is not authorized for JakeOS'),{status:403});return payload;}

async function coreJson(path,options={}){const response=await fetch(`${coreInternalUrl()}${path}`,{...options,headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})},signal:AbortSignal.timeout(Number(process.env.TUKU_AUTH_TIMEOUT_MS||8000))});const body=await response.json().catch(()=>({}));return{response,body};}

async function validateCoreAccessToken(token){const fingerprint=crypto.createHash('sha256').update(token).digest('hex'),cached=tokenCache.get(fingerprint);if(cached&&cached.expiresAt>Date.now())return cached.identity;const{response,body}=await coreJson('/api/v1/auth/me',{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw Object.assign(new Error(coreError(body,'Invalid Tuku session')),{status:response.status});const data=unwrap(body)||{},profile=data.profile||data.identity?.profile||data.identity||data;if(!profile?.coreUserId)throw new Error('Tuku identity response is incomplete');if(!ownerAllowed(profile.coreUserId))throw Object.assign(new Error('This Tuku identity is not authorized for Momentum'),{status:403});const identity={uid:profile.coreUserId,coreUserId:profile.coreUserId,email:profile.email||null,name:profile.displayName||profile.fullName||'Tuku user',provider:'tuku'};tokenCache.set(fingerprint,{identity,expiresAt:Date.now()+45000});if(tokenCache.size>200){for(const[k,v]of tokenCache)if(v.expiresAt<=Date.now())tokenCache.delete(k);}return identity;}

function requireJakeAuth(req,res,next){if(process.env.NODE_ENV==='test'&&process.env.JAKEOS_TEST_AUTH_TOKEN){const bearer=String(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1];if(bearer===process.env.JAKEOS_TEST_AUTH_TOKEN){req.tukuUser={coreUserId:'test-owner',provider:'test'};return next();}}const token=parseCookies(req)[WEB_SESSION_COOKIE];if(!token)return res.status(401).json({error:'Tuku sign-in required',code:'AUTH_REQUIRED'});try{const claims=verifyLocalSession(token);req.tukuUser={coreUserId:claims.sub,email:claims.email,organizationId:claims.organization_id,roles:claims.roles||[],permissions:claims.permissions||[],provider:'tuku'};return next();}catch(error){res.clearCookie(WEB_SESSION_COOKIE,cookieOptions());return res.status(error.status||401).json({error:error.message||'Invalid JakeOS session',code:error.status===403?'ACCESS_DENIED':'AUTH_REQUIRED'});}}

function momentumAuth(){return async(req,res,next)=>{const bearer=String(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1];if(!bearer)return res.status(401).json({error:'Tuku authentication required',code:'AUTH_REQUIRED'});if(process.env.NODE_ENV==='test'&&process.env.MOMENTUM_API_TOKEN&&bearer===process.env.MOMENTUM_API_TOKEN){req.momentumUser={uid:'test-owner',coreUserId:'test-owner',provider:'test'};return next();}try{req.momentumUser=await validateCoreAccessToken(bearer);return next();}catch(error){return res.status(error.status||401).json({error:error.message||'Invalid Tuku session',code:error.status===403?'ACCESS_DENIED':'AUTH_REQUIRED'});}};}

function webAuthRouter(){const router=express.Router();router.use(rateLimit({windowMs:60000,limit:60,standardHeaders:'draft-7',legacyHeaders:false}));
  router.post('/tuku/login',async(req,res)=>{try{const email=String(req.body?.email||'').trim().slice(0,320),password=String(req.body?.password||'').slice(0,512);if(!email||!password)return res.status(422).json({error:'Email and password are required',code:'INVALID_INPUT'});const{response,body}=await coreJson('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})});if(!response.ok)return res.status(response.status).json({error:coreError(body,'Tuku sign-in failed'),code:'AUTH_FAILED'});const data=unwrap(body)||{},user=data.user||{};if(!user.coreUserId||!ownerAllowed(user.coreUserId))return res.status(403).json({error:'This Tuku account is not authorized for JakeOS',code:'ACCESS_DENIED'});const session=signLocalSession({coreUserId:user.coreUserId,email:user.email||email},{});res.cookie(WEB_SESSION_COOKIE,session.token,cookieOptions(session.ttl*1000));res.clearCookie(PKCE_COOKIE,cookieOptions());res.clearCookie(STATE_COOKIE,cookieOptions());res.clearCookie(RETURN_COOKIE,cookieOptions());return res.set('Cache-Control','no-store').json({authenticated:true,user:{coreUserId:user.coreUserId,email:user.email||null,provider:'tuku'}});}catch(error){return res.status(502).json({error:error.message||'Tuku Auth is temporarily unavailable',code:'AUTH_UNAVAILABLE'});}});
  router.get('/tuku/start',(req,res)=>{const state=crypto.randomBytes(24).toString('base64url'),verifier=crypto.randomBytes(48).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url'),redirectUri=process.env.JAKEOS_TUKU_REDIRECT_URI||`${process.env.PUBLIC_URL||'https://jakeos.tukutuku.org'}/auth/tuku/callback`,returnTo=safeReturnTo(req.query.return_to||'/');res.cookie(PKCE_COOKIE,verifier,cookieOptions(10*60*1000));res.cookie(STATE_COOKIE,state,cookieOptions(10*60*1000));res.cookie(RETURN_COOKIE,returnTo,cookieOptions(10*60*1000));const url=new URL('/authorize',corePublicUrl());url.searchParams.set('client_id','jakeos-web');url.searchParams.set('redirect_uri',redirectUri);url.searchParams.set('state',state);url.searchParams.set('code_challenge',challenge);url.searchParams.set('code_challenge_method','S256');res.redirect(url.toString());});
  router.get('/tuku/callback',async(req,res)=>{const cookies=parseCookies(req),state=String(req.query.state||''),code=String(req.query.code||'');try{if(req.query.error)throw Object.assign(new Error(`Tuku sign-in was not completed: ${String(req.query.error)}`),{status:401});if(!state||!cookies[STATE_COOKIE]||state!==cookies[STATE_COOKIE])throw Object.assign(new Error('Tuku sign-in state could not be verified'),{status:401});if(!code||!cookies[PKCE_COOKIE])throw Object.assign(new Error('Tuku sign-in code is missing'),{status:401});const redirectUri=process.env.JAKEOS_TUKU_REDIRECT_URI||`${process.env.PUBLIC_URL||'https://jakeos.tukutuku.org'}/auth/tuku/callback`;const{response,body}=await coreJson('/api/v1/sso/exchange',{method:'POST',body:JSON.stringify({clientId:'jakeos-web',code,redirectUri,codeVerifier:cookies[PKCE_COOKIE]})});if(!response.ok)throw Object.assign(new Error(coreError(body,'Tuku sign-in exchange failed')),{status:response.status});const data=unwrap(body)||{},identity=data.identity||{},authorization=data.authorization||{};if(!identity.coreUserId||!ownerAllowed(identity.coreUserId))throw Object.assign(new Error('This Tuku account is not authorized for JakeOS'),{status:403});const session=signLocalSession(identity,authorization);res.cookie(WEB_SESSION_COOKIE,session.token,cookieOptions(session.ttl*1000));res.clearCookie(PKCE_COOKIE,cookieOptions());res.clearCookie(STATE_COOKIE,cookieOptions());const returnTo=safeReturnTo(cookies[RETURN_COOKIE]||'/');res.clearCookie(RETURN_COOKIE,cookieOptions());return res.redirect(returnTo);}catch(error){res.clearCookie(PKCE_COOKIE,cookieOptions());res.clearCookie(STATE_COOKIE,cookieOptions());res.status(error.status||500).type('html').send(`<!doctype html><meta name="viewport" content="width=device-width"><title>JakeOS sign-in</title><body style="font-family:system-ui;padding:32px;max-width:640px;margin:auto"><h1>JakeOS sign-in failed</h1><p>${String(error.message||'Unable to sign in').replace(/[<>&]/g,'')}</p><p><a href="/">Return to JakeOS</a></p></body>`);}});
  router.get('/session',requireJakeAuth,(req,res)=>res.set('Cache-Control','no-store').json({authenticated:true,user:req.tukuUser}));
  router.post('/logout',(req,res)=>{res.clearCookie(WEB_SESSION_COOKIE,cookieOptions());res.set('Cache-Control','no-store').json({signedOut:true});});
  return router;
}

function momentumAuthRouter(){const router=express.Router();router.use(rateLimit({windowMs:60000,limit:30,standardHeaders:'draft-7',legacyHeaders:false}));
  router.post('/login',async(req,res)=>{try{const email=String(req.body?.email||'').trim().slice(0,320),password=String(req.body?.password||'').slice(0,512);if(!email||!password)return res.status(422).json({error:'Email and password are required'});const{response,body}=await coreJson('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})});if(!response.ok)return res.status(response.status).json(body);const data=unwrap(body)||{};if(!ownerAllowed(data?.user?.coreUserId))return res.status(403).json({error:'This Tuku account is not authorized for Momentum',code:'ACCESS_DENIED'});return res.json(body);}catch{return res.status(502).json({error:'Tuku Auth is temporarily unavailable'});}});
  router.post('/refresh',async(req,res)=>{try{const refreshToken=String(req.body?.refreshToken||'');if(!refreshToken)return res.status(422).json({error:'Refresh token is required'});const{response,body}=await coreJson('/api/v1/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken})});if(!response.ok)return res.status(response.status).json(body);const data=unwrap(body)||{};if(!ownerAllowed(data?.user?.coreUserId))return res.status(403).json({error:'This Tuku account is not authorized for Momentum',code:'ACCESS_DENIED'});return res.json(body);}catch{return res.status(502).json({error:'Tuku Auth is temporarily unavailable'});}});
  router.get('/me',momentumAuth(),(req,res)=>res.json({authenticated:true,user:req.momentumUser}));
  router.post('/logout',momentumAuth(),async(req,res)=>{const bearer=String(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1];try{const{response,body}=await coreJson('/api/v1/auth/logout',{method:'POST',headers:{authorization:`Bearer ${bearer}`},body:JSON.stringify({allDevices:req.body?.allDevices===true})});return res.status(response.status).json(body);}catch{return res.status(502).json({error:'Tuku Auth is temporarily unavailable'});}});
  return router;
}

module.exports={requireJakeAuth,momentumAuth,webAuthRouter,momentumAuthRouter,validateCoreAccessToken,verifyLocalSession,unwrap};
